/**
 * Rama 8 — Accessory specifics
 *
 * Source: .research/materials-rama-8-accessory-specifics.md
 *
 * Coverage: 32 L1 base entries spanning chains (5), cords (6),
 *   decoration (sequins/beads/threads/feathers/crystals/pearls — 9),
 *   bag-specifics (webbing/ribbon/piping/binding/canvas/chipboard — 10),
 *   and other (faux fur, holographic film — 2).
 *
 * Layer counts:
 *   L1: 32 base entries
 *   L2: 28 size/finish/construction variants
 *   L3: 12 verified B2B suppliers
 *   ───────
 *   Total: 72 entries
 *
 * Vegan-aware: leather cord, suede cord, real feathers (ostrich / marabou),
 * cultured pearls (Akoya, Tahitian, freshwater) flagged `vegan: false`. All
 * chains, synthetic cords, plastic/glass beads, sequins, faux fur, faux pearl,
 * embroidery thread, webbing and ribbon are vegan: true.
 *
 * Excluded per Felipe's rule (brand-locked / proprietary / unverifiable):
 *   - Lululemon trim treatments, Off-White zip-tie tags
 *   - LV/GG/Hermès/Chanel/Goyard signature hardware
 *   - Real fur (mink, rabbit, fox, sable) — only ECOPEL faux fur retained
 *   - CITES-listed feathers (only farmed ostrich/marabou/pheasant kept)
 *   - Real-gold/real-silver chain >14k (jewelry catalog territory)
 *   - Non-FSC wood beads, grey-market "Swarovski-style" crystals
 *
 * Entry order: by section (chains → cords → decoration → bag-specifics →
 * other). Within each L1: L1 → L2. Suppliers (L3) grouped at the end of
 * the relevant section.
 */

import type { Material } from './types';

// ═══════════════════════════════════════════════════════════════════════
// SECTION A — CHAINS
// ═══════════════════════════════════════════════════════════════════════

const chains: Material[] = [
  // ─── 1. Curb chain ───
  {
    id: 'chain-curb',
    name: 'Curb chain',
    layer: 'L1',
    family: 'accessory-chain',
    composition: 'Brass / steel / aluminum links, twisted-flat construction',
    weightRange: { min: 2, max: 18, unit: 'mm' },
    defaultFinish: 'polished brass',
    finishOptions: ['brass', 'polished', 'gold-plated', 'gunmetal', 'nickel', 'matte', 'antique'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['crossbody', 'shoulder', 'clutch', 'jewelry', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'romantic', 'avant-garde'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'chain-curb-flat',
    name: 'Flat curb chain',
    layer: 'L2',
    parentId: 'chain-curb',
    family: 'accessory-chain',
    composition: 'Brass / steel / aluminum links, twisted-flat construction',
    weightRange: { min: 3, max: 15, unit: 'mm' },
    defaultFinish: 'polished',
    zones: ['Hardware', 'Strap'],
    subtypes: ['crossbody', 'shoulder', 'jewelry'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'chain-curb-chunky',
    name: 'Chunky curb chain',
    layer: 'L2',
    parentId: 'chain-curb',
    family: 'accessory-chain',
    composition: 'Brass / steel / aluminum links, twisted-flat construction',
    weightRange: { min: 10, max: 20, unit: 'mm' },
    defaultFinish: 'gold-plated',
    zones: ['Strap', 'Hardware'],
    subtypes: ['shoulder', 'crossbody', 'jewelry'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'romantic', 'avant-garde'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 2. Figaro chain ───
  {
    id: 'chain-figaro',
    name: 'Figaro chain',
    layer: 'L1',
    family: 'accessory-chain',
    composition: 'Brass / steel, alternating short-long oval links (3+1 pattern)',
    weightRange: { min: 2, max: 12, unit: 'mm' },
    defaultFinish: 'gold-plated',
    finishOptions: ['brass', 'gold-plated', 'silver-plated', 'gunmetal', 'nickel'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['jewelry', 'crossbody', 'belt'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 3. Rolo (belcher) chain ───
  {
    id: 'chain-rolo',
    name: 'Rolo chain',
    layer: 'L1',
    family: 'accessory-chain',
    composition: 'Brass / steel, identical round links',
    weightRange: { min: 2, max: 10, unit: 'mm' },
    defaultFinish: 'polished brass',
    finishOptions: ['brass', 'gold-plated', 'silver-plated', 'gunmetal', 'matte'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['jewelry', 'crossbody', 'clutch'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 4. Box chain ───
  {
    id: 'chain-box',
    name: 'Box chain',
    layer: 'L1',
    family: 'accessory-chain',
    composition: 'Steel / brass square cross-section links',
    weightRange: { min: 1, max: 6, unit: 'mm' },
    defaultFinish: 'polished',
    finishOptions: ['brass', 'gold-plated', 'silver-plated', 'gunmetal'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['jewelry', 'eyewear'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 5. Aluminum chain ───
  {
    id: 'chain-aluminum',
    name: 'Aluminum chain',
    layer: 'L1',
    family: 'accessory-chain',
    composition: 'Lightweight anodized aluminum links',
    weightRange: { min: 4, max: 22, unit: 'mm' },
    defaultFinish: 'anodized matte',
    finishOptions: ['matte', 'polished', 'colored anodized', 'gold-anodized', 'gunmetal'],
    zones: ['Strap', 'Hardware'],
    subtypes: ['crossbody', 'shoulder', 'clutch'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'streetwear', 'avant-garde'],
    seasonFit: ['SS', 'all-year'],
    vegan: true,
  },
  {
    id: 'chain-aluminum-oversized',
    name: 'Oversized anodized aluminum chain',
    layer: 'L2',
    parentId: 'chain-aluminum',
    family: 'accessory-chain',
    composition: 'Lightweight anodized aluminum links',
    weightRange: { min: 15, max: 30, unit: 'mm' },
    defaultFinish: 'matte black',
    zones: ['Strap'],
    subtypes: ['shoulder', 'clutch'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['streetwear', 'avant-garde'],
    seasonFit: ['SS', 'all-year'],
    vegan: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════
// SECTION B — CORDS
// ═══════════════════════════════════════════════════════════════════════

const cords: Material[] = [
  // ─── 6. Paracord ───
  {
    id: 'cord-paracord',
    name: 'Paracord (550 / 750)',
    layer: 'L1',
    family: 'accessory-cord',
    composition: 'Nylon kernmantle (sheath + 7–11 inner yarn cores)',
    weightRange: { min: 4, max: 5, unit: 'mm' },
    defaultFinish: '550 (550 lb tensile)',
    finishOptions: ['550', '750', 'reflective sheath', 'glow-in-dark'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['crossbody', 'backpack', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['utility', 'sport', 'streetwear', 'avant-garde'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cord-paracord-550',
    name: 'Paracord 550',
    layer: 'L2',
    parentId: 'cord-paracord',
    family: 'accessory-cord',
    composition: 'Nylon kernmantle, 7 inner cores (550 lb tensile)',
    weightRange: { min: 4, max: 4, unit: 'mm' },
    defaultFinish: '7 inner cores',
    zones: ['Hardware', 'Strap'],
    subtypes: ['crossbody', 'backpack'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['utility', 'sport', 'streetwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cord-paracord-750',
    name: 'Paracord 750',
    layer: 'L2',
    parentId: 'cord-paracord',
    family: 'accessory-cord',
    composition: 'Nylon kernmantle, 11 inner cores (750 lb tensile)',
    weightRange: { min: 4, max: 5, unit: 'mm' },
    defaultFinish: '11 inner cores (750 lb tensile)',
    zones: ['Hardware', 'Strap'],
    subtypes: ['backpack', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['utility', 'sport', 'streetwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 7. Waxed cotton cord ───
  {
    id: 'cord-waxed-cotton',
    name: 'Waxed cotton cord',
    layer: 'L1',
    family: 'accessory-cord',
    composition: 'Twisted cotton yarn impregnated with paraffin / beeswax',
    weightRange: { min: 1, max: 3, unit: 'mm' },
    defaultFinish: 'natural waxed',
    finishOptions: ['natural', 'black', 'brown', 'colored-dyed'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['jewelry', 'scarf', 'clutch'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 8. Jute rope ───
  {
    id: 'cord-jute-rope',
    name: 'Jute rope',
    layer: 'L1',
    family: 'accessory-cord',
    composition: '100% natural jute fiber, twisted',
    weightRange: { min: 3, max: 12, unit: 'mm' },
    defaultFinish: 'natural',
    finishOptions: ['natural', 'bleached', 'dyed'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['tote', 'hat'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['romantic', 'resort', 'bohemian'],
    seasonFit: ['SS'],
    vegan: true,
  },

  // ─── 9. Leather cord ───
  {
    id: 'cord-leather',
    name: 'Leather cord',
    layer: 'L1',
    family: 'accessory-cord',
    composition: 'Round-cut bovine leather, oil-tanned',
    weightRange: { min: 1, max: 5, unit: 'mm' },
    defaultFinish: 'natural',
    finishOptions: ['natural', 'black', 'brown', 'braided'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['jewelry', 'clutch', 'belt', 'hat'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: false,
  },

  // ─── 10. Suede cord ───
  {
    id: 'cord-suede',
    name: 'Suede cord',
    layer: 'L1',
    family: 'accessory-cord',
    composition: 'Split bovine suede, flat-cut',
    weightRange: { min: 2, max: 5, unit: 'mm' },
    defaultFinish: 'natural',
    finishOptions: ['natural', 'colored-dyed', 'black', 'tan'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['jewelry', 'hat', 'scarf'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: false,
  },

  // ─── 11. Cotton drawstring cord ───
  {
    id: 'cord-cotton-drawstring',
    name: 'Cotton drawstring cord',
    layer: 'L1',
    family: 'accessory-cord',
    composition: 'Braided / twisted cotton yarn',
    weightRange: { min: 3, max: 8, unit: 'mm' },
    defaultFinish: 'natural braided',
    finishOptions: ['natural', 'white', 'black', 'colored', 'tipped'],
    zones: ['Hardware', 'Strap'],
    subtypes: ['backpack', 'tote', 'hat'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════
// SECTION C — DECORATION
// (sequins / beads / embroidery / feathers / crystals / pearls)
// ═══════════════════════════════════════════════════════════════════════

const decoration: Material[] = [
  // ─── 12. Sequins ───
  {
    id: 'deco-sequins',
    name: 'Sequins',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'PET / PVC / metal foil / bioplastic disc, flat or cup',
    weightRange: { min: 3, max: 25, unit: 'mm' },
    defaultFinish: 'shiny',
    finishOptions: ['shiny', 'matte', 'iridescent', 'holographic', 'metallic', 'laser-cut'],
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'dress', 'blouse', 'top'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic', 'avant-garde'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
  },
  {
    id: 'deco-sequins-plastic',
    name: 'Plastic sequins (PET)',
    layer: 'L2',
    parentId: 'deco-sequins',
    family: 'accessory-decoration',
    composition: 'PET disc, recyclable',
    weightRange: { min: 3, max: 20, unit: 'mm' },
    defaultFinish: 'shiny',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'dress', 'blouse', 'top'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
  },
  {
    id: 'deco-sequins-metal',
    name: 'Metal sequins (foil)',
    layer: 'L2',
    parentId: 'deco-sequins',
    family: 'accessory-decoration',
    composition: 'Aluminum / brass foil, stamped',
    weightRange: { min: 3, max: 15, unit: 'mm' },
    defaultFinish: 'polished metal',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'dress', 'top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
  },
  {
    id: 'deco-sequins-bioplastic',
    name: 'Bioplastic sequins (cellulose)',
    layer: 'L2',
    parentId: 'deco-sequins',
    family: 'accessory-decoration',
    composition: 'Cellulose / PLA biopolymer disc, biodegradable',
    weightRange: { min: 3, max: 20, unit: 'mm' },
    defaultFinish: 'matte / iridescent',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'dress', 'blouse'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['sustainable', 'romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
  },

  // ─── 13. Czech glass beads ───
  {
    id: 'deco-bead-glass-czech',
    name: 'Czech glass beads',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Soda-lime glass, fire-polished or pressed',
    weightRange: { min: 2, max: 12, unit: 'mm' },
    defaultFinish: 'polished glass',
    finishOptions: ['polished', 'matte', 'AB-coated', 'metallic', 'opaque', 'transparent'],
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'dress', 'top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 14. Japanese seed beads ───
  {
    id: 'deco-bead-seed-japanese',
    name: 'Japanese seed beads',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Precision-cut Japanese soda-lime glass cylinders / rounds',
    weightRange: { min: 1.3, max: 4, unit: 'mm' },
    defaultFinish: '11/0 round (default sizing)',
    finishOptions: ['6/0', '8/0', '11/0', '15/0', 'Delica cylinder', 'metallic', 'silver-lined', 'matte AB'],
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch', 'scarf', 'dress', 'top'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'deco-bead-seed-11-0',
    name: 'Seed bead 11/0',
    layer: 'L2',
    parentId: 'deco-bead-seed-japanese',
    family: 'accessory-decoration',
    composition: 'Precision-cut Japanese soda-lime glass round',
    weightRange: { min: 2.0, max: 2.2, unit: 'mm' },
    defaultFinish: 'round',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'deco-bead-seed-15-0',
    name: 'Seed bead 15/0',
    layer: 'L2',
    parentId: 'deco-bead-seed-japanese',
    family: 'accessory-decoration',
    composition: 'Precision-cut Japanese soda-lime glass round',
    weightRange: { min: 1.3, max: 1.5, unit: 'mm' },
    defaultFinish: 'round',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'deco-bead-delica',
    name: 'Delica cylinder bead',
    layer: 'L2',
    parentId: 'deco-bead-seed-japanese',
    family: 'accessory-decoration',
    composition: 'Precision-cut Japanese soda-lime glass cylinder',
    weightRange: { min: 1.6, max: 1.6, unit: 'mm' },
    defaultFinish: 'precision cylinder',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 15. Wood beads ───
  {
    id: 'deco-bead-wood',
    name: 'Wood beads (sustainably-harvested)',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'FSC-certified hardwood (beech / maple / olive), drilled & sanded',
    weightRange: { min: 6, max: 30, unit: 'mm' },
    defaultFinish: 'natural waxed',
    finishOptions: ['natural', 'stained', 'painted', 'lacquered'],
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'tote', 'hat'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['resort', 'bohemian'],
    seasonFit: ['SS', 'all-year'],
    certifications: ['FSC'],
    vegan: true,
  },

  // ─── 16. Plastic / resin beads ───
  {
    id: 'deco-bead-resin',
    name: 'Plastic / resin beads',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Acrylic / polyester resin / PMMA, molded',
    weightRange: { min: 4, max: 30, unit: 'mm' },
    defaultFinish: 'polished',
    finishOptions: ['polished', 'matte', 'translucent', 'opaque', 'marbled', 'faceted'],
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch', 'hat'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['avant-garde', 'romantic'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 17. Embroidery thread ───
  {
    id: 'deco-thread-embroidery',
    name: 'Embroidery thread',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Mercerized cotton / poly trilobal / silk filament / metallic-wrapped',
    weightRange: { min: 30, max: 60, unit: 'denier' },
    defaultFinish: '40 wt poly trilobal',
    finishOptions: ['cotton', 'poly trilobal', 'silk', 'metallic', 'variegated'],
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'hat', 'tote', 'dress', 'blouse', 'top', 'shirt'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'deco-thread-cotton',
    name: 'Cotton embroidery thread',
    layer: 'L2',
    parentId: 'deco-thread-embroidery',
    family: 'accessory-decoration',
    composition: 'Mercerized 6-strand cotton (DMC-equivalent)',
    weightRange: { min: 30, max: 60, unit: 'denier' },
    defaultFinish: 'matte cotton',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'dress', 'blouse', 'shirt'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'deco-thread-poly',
    name: 'Polyester embroidery thread',
    layer: 'L2',
    parentId: 'deco-thread-embroidery',
    family: 'accessory-decoration',
    composition: 'Trilobal polyester filament',
    weightRange: { min: 30, max: 60, unit: 'denier' },
    defaultFinish: 'high-sheen poly',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'hat', 'dress', 'blouse', 'top', 'shirt'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['sport', 'streetwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'deco-thread-silk',
    name: 'Silk embroidery thread',
    layer: 'L2',
    parentId: 'deco-thread-embroidery',
    family: 'accessory-decoration',
    composition: '100% mulberry silk filament',
    weightRange: { min: 30, max: 60, unit: 'denier' },
    defaultFinish: 'natural sheen',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'dress', 'blouse', 'top'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: false,
  },
  {
    id: 'deco-thread-metallic',
    name: 'Metallic embroidery thread',
    layer: 'L2',
    parentId: 'deco-thread-embroidery',
    family: 'accessory-decoration',
    composition: 'Polyester core wrapped with metalized film',
    weightRange: { min: 30, max: 60, unit: 'denier' },
    defaultFinish: 'gold / silver metallic',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'dress', 'blouse', 'top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 18. Feathers ───
  {
    id: 'deco-feather',
    name: 'Feathers (farmed, non-CITES)',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Ostrich / marabou / pheasant — farmed, non-CITES species',
    weightRange: { min: 30, max: 200, unit: 'mm' },
    defaultFinish: 'natural',
    finishOptions: ['natural', 'dyed', 'tipped', 'fluffed'],
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'hat', 'scarf'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'avant-garde'],
    seasonFit: ['FW', 'all-year'],
    vegan: false,
  },
  {
    id: 'deco-feather-ostrich',
    name: 'Ostrich feather',
    layer: 'L2',
    parentId: 'deco-feather',
    family: 'accessory-decoration',
    composition: 'Farmed ostrich feather (non-CITES)',
    weightRange: { min: 100, max: 200, unit: 'mm' },
    defaultFinish: 'natural fluffed',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'hat', 'scarf'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['FW', 'all-year'],
    vegan: false,
  },
  {
    id: 'deco-feather-marabou',
    name: 'Marabou feather',
    layer: 'L2',
    parentId: 'deco-feather',
    family: 'accessory-decoration',
    composition: 'Farmed marabou (turkey-derived) feather (non-CITES)',
    weightRange: { min: 30, max: 80, unit: 'mm' },
    defaultFinish: 'natural fluffed',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'hat', 'scarf'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'avant-garde'],
    seasonFit: ['FW', 'all-year'],
    vegan: false,
  },

  // ─── 19. Crystals ───
  {
    id: 'deco-crystal',
    name: 'Crystal (cut leaded glass)',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Lead-free / leaded cut glass with foil-back coating',
    weightRange: { min: 2, max: 30, unit: 'mm' },
    defaultFinish: 'Crystal Clear',
    finishOptions: ['Crystal', 'AB', 'Jet', 'colored', 'unfoiled', 'sew-on', 'hot-fix', 'flat-back'],
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'hat', 'dress', 'top'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
  },
  {
    id: 'deco-crystal-flatback',
    name: 'Flat-back crystal (hot-fix / glue-on)',
    layer: 'L2',
    parentId: 'deco-crystal',
    family: 'accessory-decoration',
    composition: 'Lead-free cut glass, foil-back, hot-fix or glue-on',
    weightRange: { min: 2, max: 8, unit: 'mm' },
    defaultFinish: 'foil-back',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'scarf', 'hat', 'dress', 'top'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
  },
  {
    id: 'deco-crystal-pointed-back',
    name: 'Pointed-back crystal (chaton)',
    layer: 'L2',
    parentId: 'deco-crystal',
    family: 'accessory-decoration',
    composition: 'Lead-free cut glass, foil-back chaton',
    weightRange: { min: 3, max: 12, unit: 'mm' },
    defaultFinish: 'foil-back chaton',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
  },
  {
    id: 'deco-crystal-sew-on',
    name: 'Sew-on crystal',
    layer: 'L2',
    parentId: 'deco-crystal',
    family: 'accessory-decoration',
    composition: 'Lead-free cut glass with two-hole sew channel',
    weightRange: { min: 6, max: 30, unit: 'mm' },
    defaultFinish: 'two-hole sew',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'scarf', 'dress'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
  },

  // ─── 20. Pearls ───
  {
    id: 'deco-pearl',
    name: 'Pearls',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Cultured (Akoya/Tahitian/freshwater) or synthetic glass-based with nacre coating',
    weightRange: { min: 2, max: 16, unit: 'mm' },
    defaultFinish: 'white round',
    finishOptions: ['white', 'cream', 'black', 'baroque', 'faux glass', 'cultured'],
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch', 'scarf'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: false,
    notes: 'Mixed L1: cultured pearls are vegan: false; faux-glass variants under L2 (deco-pearl-faux-glass) are vegan: true.',
  },
  {
    id: 'deco-pearl-cultured-akoya',
    name: 'Cultured Akoya pearl',
    layer: 'L2',
    parentId: 'deco-pearl',
    family: 'accessory-decoration',
    composition: 'Cultured Akoya pearl (saltwater, oyster-derived nacre)',
    weightRange: { min: 3, max: 10, unit: 'mm' },
    defaultFinish: 'white-rosé round',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: false,
  },
  {
    id: 'deco-pearl-cultured-tahitian',
    name: 'Cultured Tahitian pearl',
    layer: 'L2',
    parentId: 'deco-pearl',
    family: 'accessory-decoration',
    composition: 'Cultured Tahitian pearl (saltwater, black-lipped oyster)',
    weightRange: { min: 8, max: 16, unit: 'mm' },
    defaultFinish: 'black-peacock',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['avant-garde', 'romantic'],
    seasonFit: ['all-year'],
    vegan: false,
  },
  {
    id: 'deco-pearl-freshwater',
    name: 'Cultured freshwater pearl (often baroque)',
    layer: 'L2',
    parentId: 'deco-pearl',
    family: 'accessory-decoration',
    composition: 'Cultured freshwater pearl (mussel-derived, baroque shape)',
    weightRange: { min: 4, max: 14, unit: 'mm' },
    defaultFinish: 'baroque shape',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: false,
  },
  {
    id: 'deco-pearl-faux-glass',
    name: 'Faux pearl (glass core, nacre coating)',
    layer: 'L2',
    parentId: 'deco-pearl',
    family: 'accessory-decoration',
    composition: 'Glass core with synthetic nacre coating (Majorica-style)',
    weightRange: { min: 3, max: 16, unit: 'mm' },
    defaultFinish: 'white round (Majorica-style)',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch', 'scarf'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── L3 — Decoration suppliers ───
  {
    id: 'supplier-swarovski',
    name: 'Swarovski Components',
    layer: 'L3',
    parentId: 'deco-crystal',
    family: 'accessory-decoration',
    composition: 'Crystal components (Xirius pointed-back, flat-back hot-fix, sew-on, Crystal Pearl, Created Diamonds)',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'hat', 'dress', 'top'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
    supplier: {
      origin: 'Wattens, Austria',
      tier: 'trim-maker',
      verificationUrl: 'https://www.swarovski.com/en-US/c-cb1/business/',
    },
    notes: 'Open B2B division (Components). Discontinued certain consumer-facing flat-back lines 2021 but B2B catalog robust.',
  },
  {
    id: 'supplier-preciosa',
    name: 'Preciosa Components',
    layer: 'L3',
    parentId: 'deco-crystal',
    family: 'accessory-decoration',
    composition: 'MAXIMA chaton, VIVA crystals, Rocailles seed beads, sew-on, flat-back',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'jewelry', 'scarf', 'hat', 'dress', 'top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year', 'FW'],
    vegan: true,
    supplier: {
      origin: 'Jablonec nad Nisou, Czech Republic',
      tier: 'trim-maker',
      verificationUrl: 'https://www.preciosa.com/en/products/',
    },
    notes: 'Czech crystal heritage. Open B2B catalog including Rocailles seed beads.',
  },
  {
    id: 'supplier-toho',
    name: 'Toho Beads',
    layer: 'L3',
    parentId: 'deco-bead-seed-japanese',
    family: 'accessory-decoration',
    composition: 'Round seed 6/0–15/0, cube, triangle, Aiko cylinder, Treasure',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch', 'scarf'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Hiroshima, Japan',
      tier: 'trim-maker',
      verificationUrl: 'https://www.tohobeads.net/',
    },
    notes: 'One of two dominant Japanese seed bead houses. Open B2B distribution via Shipwreck Beads (US), Bohemian Findings (EU).',
  },
  {
    id: 'supplier-miyuki',
    name: 'Miyuki Co.',
    layer: 'L3',
    parentId: 'deco-bead-seed-japanese',
    family: 'accessory-decoration',
    composition: 'Round seed 6/0–15/0, Delica cylinder (DB/DBL/DBM/DBS), Tila, Half Tila, drops',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch', 'scarf'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Hiroshima, Japan',
      tier: 'trim-maker',
      verificationUrl: 'https://www.miyuki-beads.co.jp/english/',
    },
    notes: 'Inventor of Delica cylinder bead. Industry standard for bead-loom embroidery; open B2B.',
  },
  {
    id: 'supplier-madeira',
    name: 'Madeira',
    layer: 'L3',
    parentId: 'deco-thread-embroidery',
    family: 'accessory-decoration',
    composition: 'Polyneon poly, Classic rayon, Cotona cotton, Metallic FS, Frosted Matt',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'hat', 'dress', 'blouse', 'top', 'shirt'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic', 'sport'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Freiburg, Germany',
      tier: 'component-maker',
      verificationUrl: 'https://www.madeirausa.com/',
    },
    notes: 'Industry-standard machine embroidery thread. B2B catalog open globally.',
  },
  {
    id: 'supplier-robison-anton',
    name: 'Robison-Anton',
    layer: 'L3',
    parentId: 'deco-thread-embroidery',
    family: 'accessory-decoration',
    composition: 'Super Strength rayon, poly J, metallic, cotton machine',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'hat', 'dress', 'blouse', 'top', 'shirt'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic', 'sport'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Fairview, NJ, USA',
      tier: 'component-maker',
      verificationUrl: 'https://www.robison-anton.com/',
    },
    notes: 'US industry standard alongside Madeira. Acquired by American & Efird (now Coats subsidiary) but RA brand maintained.',
  },
  {
    id: 'supplier-coats-astra',
    name: 'Coats (Astra)',
    layer: 'L3',
    parentId: 'deco-thread-embroidery',
    family: 'accessory-decoration',
    composition: 'Astra poly embroidery, Sylko core, Gramax bonded, Eco threads',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'hat', 'dress', 'blouse', 'top', 'shirt'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['sport', 'romantic'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'United Kingdom (global operations)',
      tier: 'component-maker',
      verificationUrl: 'https://www.coats.com/',
    },
    notes: 'Global thread giant. Astra is their machine-embroidery range; full B2B.',
  },
  {
    id: 'supplier-mikimoto',
    name: 'Mikimoto',
    layer: 'L3',
    parentId: 'deco-pearl',
    family: 'accessory-decoration',
    composition: 'Akoya cultured pearl (signature), South Sea white, Tahitian black, strands, loose',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry'],
    priceTier: ['luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: false,
    supplier: {
      origin: 'Toba, Mie, Japan',
      tier: 'component-maker',
      verificationUrl: 'https://www.mikimoto.com/',
    },
    notes: 'Founder of cultured pearl industry (1893). Primarily a finished-jewelry house but B2B wholesale division (Mikimoto Pearl Co.) verified open to atelier brands. CAVEAT: minimum order quantity applies and lead times must be verified before specifying.',
  },
  {
    id: 'supplier-majorica',
    name: 'Majorica',
    layer: 'L3',
    parentId: 'deco-pearl',
    family: 'accessory-decoration',
    composition: 'Faux glass-core pearl with Iridia nacre coating, loose strands, ready-set components',
    zones: ['Trim', 'Branding'],
    subtypes: ['jewelry', 'clutch', 'scarf'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Manacor, Mallorca, Spain',
      tier: 'component-maker',
      verificationUrl: 'https://www.majorica.com/',
    },
    notes: 'Founded 1890. Open B2B catalog of loose pearls + components for designers; their patented Iridia coating is industry reference for faux pearl.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// SECTION D — BAG-SPECIFICS
// (webbing / ribbon / piping / binding / canvas / chipboard)
// ═══════════════════════════════════════════════════════════════════════

const bagSpecifics: Material[] = [
  // ─── 21. Cotton webbing ───
  {
    id: 'web-cotton',
    name: 'Cotton webbing',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: '100% cotton, plain or twill weave',
    weightRange: { min: 10, max: 50, unit: 'mm' },
    defaultFinish: 'natural',
    finishOptions: ['natural', 'dyed', 'striped', 'logo-jacquard'],
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['tote', 'crossbody', 'backpack', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'web-cotton-25',
    name: 'Cotton webbing 25mm',
    layer: 'L2',
    parentId: 'web-cotton',
    family: 'accessory-decoration',
    composition: '100% cotton, plain or twill weave',
    weightRange: { min: 25, max: 25, unit: 'mm' },
    defaultFinish: 'natural',
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['tote', 'crossbody', 'backpack', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'web-cotton-38',
    name: 'Cotton webbing 38mm',
    layer: 'L2',
    parentId: 'web-cotton',
    family: 'accessory-decoration',
    composition: '100% cotton, plain or twill weave',
    weightRange: { min: 38, max: 38, unit: 'mm' },
    defaultFinish: 'natural',
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['tote', 'crossbody', 'backpack', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 22. Nylon webbing ───
  {
    id: 'web-nylon',
    name: 'Nylon webbing',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: '100% nylon 6 / 6,6 — high tensile',
    weightRange: { min: 10, max: 50, unit: 'mm' },
    defaultFinish: 'smooth',
    finishOptions: ['smooth', 'jacquard', 'reflective', 'colored'],
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['backpack', 'crossbody', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'utility', 'streetwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 23. Polyester webbing ───
  {
    id: 'web-polyester',
    name: 'Polyester webbing',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: '100% PET — UV-stable',
    weightRange: { min: 10, max: 50, unit: 'mm' },
    defaultFinish: 'smooth',
    finishOptions: ['smooth', 'jacquard', 'logo-print', 'recycled-PET'],
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['backpack', 'crossbody', 'tote', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'utility', 'streetwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 24. Grosgrain ribbon ───
  {
    id: 'ribbon-grosgrain',
    name: 'Grosgrain ribbon',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Polyester / cotton / silk, ribbed weft-faced weave',
    weightRange: { min: 6, max: 50, unit: 'mm' },
    defaultFinish: 'ribbed',
    finishOptions: ['polyester', 'cotton', 'silk', 'jacquard-logo'],
    zones: ['Body', 'Strap', 'Trim', 'Branding'],
    subtypes: ['hat', 'scarf', 'clutch', 'jewelry'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 25. Satin ribbon ───
  {
    id: 'ribbon-satin',
    name: 'Satin ribbon',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Polyester / silk, satin weave (high lustre face)',
    weightRange: { min: 3, max: 75, unit: 'mm' },
    defaultFinish: 'single-face satin',
    finishOptions: ['single-face', 'double-face', 'silk', 'poly'],
    zones: ['Body', 'Strap', 'Trim', 'Branding'],
    subtypes: ['clutch', 'hat', 'scarf', 'jewelry'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 26. Twill tape ───
  {
    id: 'ribbon-twill-tape',
    name: 'Twill tape',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Cotton / poly twill weave, herringbone',
    weightRange: { min: 6, max: 25, unit: 'mm' },
    defaultFinish: 'natural',
    finishOptions: ['cotton', 'poly', 'herringbone', 'logo-printed'],
    zones: ['Body', 'Strap', 'Trim', 'Branding'],
    subtypes: ['tote', 'backpack', 'crossbody'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['minimal', 'utility'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 27. Piping cord ───
  {
    id: 'piping-foam-core',
    name: 'Piping cord (foam-core)',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'PE foam core wrapped in fabric (cotton / leather / poly)',
    weightRange: { min: 2, max: 8, unit: 'mm' },
    defaultFinish: 'fabric-wrapped',
    finishOptions: ['cotton-wrap', 'leather-wrap', 'poly-wrap', 'contrast-color'],
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['tote', 'crossbody', 'clutch', 'belt'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 28. Bias binding ───
  {
    id: 'bias-binding',
    name: 'Bias binding',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Cotton / poly / silk satin, cut on 45° bias',
    weightRange: { min: 10, max: 30, unit: 'mm' },
    defaultFinish: 'single-fold',
    finishOptions: ['cotton', 'poly', 'silk-satin', 'double-fold'],
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['scarf', 'clutch', 'tote'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 29. Canvas reinforcement ───
  {
    id: 'canvas-reinforcement',
    name: 'Canvas reinforcement',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Heavy cotton duck or poly canvas (12–18 oz), used as inner base/wall stiffener',
    weightRange: { min: 12, max: 18, unit: 'oz/yd2' },
    defaultFinish: 'natural',
    finishOptions: ['natural', 'sized', 'wax-finished'],
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['tote', 'crossbody', 'backpack', 'clutch'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['utility'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── 30. Chipboard / cardboard stiffener ───
  {
    id: 'stiffener-chipboard',
    name: 'Chipboard / cardboard stiffener',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Recycled paper chipboard, 30–60 pt thickness',
    weightRange: { min: 0.8, max: 1.5, unit: 'mm' },
    defaultFinish: 'grey natural',
    finishOptions: ['grey', 'kraft', 'laminated', 'plastic-coated'],
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['clutch', 'tote', 'backpack'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['utility'],
    seasonFit: ['all-year'],
    vegan: true,
  },

  // ─── L3 — Bag-specifics suppliers ───
  {
    id: 'supplier-national-webbing',
    name: 'National Webbing Products',
    layer: 'L3',
    parentId: 'web-nylon',
    family: 'accessory-decoration',
    composition: 'Nylon webbing, poly webbing, cotton webbing, elastic, custom widths/colors',
    zones: ['Body', 'Strap', 'Trim'],
    subtypes: ['tote', 'crossbody', 'backpack', 'belt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'utility', 'streetwear'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Long Island, NY, USA',
      tier: 'finisher',
      verificationUrl: 'https://www.nationalwebbing.com/',
    },
    notes: 'Open B2B with full custom-width / custom-color program. Domestic US production.',
  },
  {
    id: 'supplier-bally-ribbon',
    name: 'Bally Ribbon Mills',
    layer: 'L3',
    parentId: 'ribbon-grosgrain',
    family: 'accessory-decoration',
    composition: 'Grosgrain, jacquard logo ribbon, webbing, narrow-fabric technical',
    zones: ['Body', 'Strap', 'Trim', 'Branding'],
    subtypes: ['hat', 'scarf', 'clutch', 'jewelry', 'tote', 'crossbody'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Bally, Pennsylvania, USA',
      tier: 'finisher',
      verificationUrl: 'https://www.ballyribbon.com/',
    },
    notes: 'Open B2B. Same mill that supplies aerospace narrow-fabrics also runs decorative jacquard programs for fashion houses.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// SECTION E — OTHER (faux fur, holographic film)
// ═══════════════════════════════════════════════════════════════════════

const other: Material[] = [
  // ─── 31. Faux fur ───
  {
    id: 'faux-fur',
    name: 'Faux fur',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Acrylic / modacrylic / polyester pile knitted onto poly backing',
    weightRange: { min: 10, max: 80, unit: 'mm' },
    defaultFinish: 'long-pile shaggy',
    finishOptions: ['short-pile', 'long-pile shaggy', 'sheared', 'grooved', 'tipped', 'colored'],
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'hat'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic', 'streetwear'],
    seasonFit: ['FW'],
    vegan: true,
  },
  {
    id: 'faux-fur-shaggy',
    name: 'Long-pile shaggy faux fur',
    layer: 'L2',
    parentId: 'faux-fur',
    family: 'accessory-decoration',
    composition: 'Acrylic / modacrylic shaggy pile on poly backing',
    weightRange: { min: 40, max: 80, unit: 'mm' },
    defaultFinish: 'shaggy',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'hat'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic'],
    seasonFit: ['FW'],
    vegan: true,
  },
  {
    id: 'faux-fur-sheared',
    name: 'Sheared faux fur',
    layer: 'L2',
    parentId: 'faux-fur',
    family: 'accessory-decoration',
    composition: 'Acrylic / modacrylic sheared pile, velvet-cut',
    weightRange: { min: 8, max: 20, unit: 'mm' },
    defaultFinish: 'velvet-cut',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'hat'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal'],
    seasonFit: ['FW'],
    vegan: true,
  },
  {
    id: 'supplier-ecopel',
    name: 'ECOPEL',
    layer: 'L3',
    parentId: 'faux-fur',
    family: 'accessory-decoration',
    composition: 'KOBA bio-based fur, recycled-PET fur, modacrylic shaggy, sheared, grooved, custom colors',
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'scarf', 'hat'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['sustainable', 'romantic'],
    seasonFit: ['FW'],
    vegan: true,
    supplier: {
      origin: 'Roubaix, France (production: China/France)',
      tier: 'mill',
      verificationUrl: 'https://ecopel.com/',
    },
    notes: 'Industry leader. Open B2B serving Stella McCartney, Chloé, Gucci, Burberry. KOBA range = corn-derived bio-fur (DuPont Sorona blend).',
  },

  // ─── 32. Holographic film ───
  {
    id: 'holographic-film',
    name: 'Holographic film (handbag accent)',
    layer: 'L1',
    family: 'accessory-decoration',
    composition: 'Metallized polyester / TPU film with diffraction-grating coating',
    weightRange: { min: 50, max: 200, unit: 'micron' },
    defaultFinish: 'iridescent silver',
    finishOptions: ['iridescent', 'rainbow', 'prism', 'colored', 'matte-holo'],
    zones: ['Trim', 'Branding'],
    subtypes: ['clutch', 'tote', 'crossbody', 'jewelry'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['avant-garde', 'sport', 'streetwear'],
    seasonFit: ['SS', 'all-year'],
    vegan: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════
// AGGREGATE — Rama 8 complete (32 L1 + 28 L2 + 12 L3 = 72 entries)
// ═══════════════════════════════════════════════════════════════════════

export const rama8: Material[] = [
  ...chains,
  ...cords,
  ...decoration,
  ...bagSpecifics,
  ...other,
];
