/**
 * Rama 1 — Natural textile fibers
 *
 * Source: .research/materials-rama-1-natural-fibers.md (R2 cleanup applied
 * 2026-05-04 per Felipe's "si no está claro, fuera" rule).
 *
 * Coverage: 21 fibers (10 cellulosic + 11 animal).
 *   Cellulosic: cotton, linen, hemp, ramie, jute, bamboo, abaca, piña, kapok, nettle
 *   Animal:     wool, cashmere, mohair, alpaca, angora, vicuña, llama, camel hair, yak, qiviut, silk
 *
 * Layer counts:
 *   L1: 21 base entries
 *   L2: 92 construction × weight × finish variants
 *   L3: 47 verified B2B mill suppliers
 *   ───────
 *   Total: ~160 entries
 *
 * Entry order: by fiber section (matches markdown). Within fiber: L1 → L2 → L3.
 */

import type { Material } from './types';

// ═══════════════════════════════════════════════════════════════════════
// 1. COTTON
// ═══════════════════════════════════════════════════════════════════════

const cotton: Material[] = [
  // ─── L1 ───
  {
    id: 'cotton',
    name: 'Cotton',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 80, max: 450, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'sanforized', 'mercerized', 'garment-washed', 'stonewashed', 'brushed', 'peached', 'enzyme-washed', 'resin-finished'],
    zones: ['Body', 'Lining', 'Collar', 'Cuff', 'Pocket', 'Sleeve'],
    subtypes: ['dress', 'top', 'shirt', 'blouse', 'tshirt', 'polo', 'bottom', 'trouser', 'jean', 'short', 'skirt', 'jumpsuit', 'outerwear-jacket', 'blazer', 'suit', 'lingerie', 'loungewear', 'activewear'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored', 'streetwear', 'workwear', 'preppy', 'sport', 'sustainable', 'utility', 'resort'],
    seasonFit: ['SS', 'FW', 'transitional', 'all-year'],
    certifications: ['OEKO-TEX', 'GOTS', 'BCI', 'Organic-Content-Standard', 'Fair-Trade', 'Cradle-to-Cradle'],
    vegan: true,
  },

  // ─── L2 — Construction × weight × finish ───
  {
    id: 'cotton-poplin',
    name: 'Cotton poplin',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 90, max: 130, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored', 'preppy'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-twill',
    name: 'Cotton twill',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 180, max: 320, unit: 'gsm' },
    defaultFinish: 'sanforized',
    zones: ['Body', 'Sleeve', 'Pocket'],
    subtypes: ['trouser', 'short', 'outerwear-jacket', 'skirt', 'shirt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'tailored', 'preppy'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'cotton-oxford',
    name: 'Cotton oxford',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt', 'blouse'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['preppy', 'tailored', 'workwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-pinpoint-oxford',
    name: 'Pinpoint oxford',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 110, max: 150, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-voile',
    name: 'Cotton voile',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 60, max: 100, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body', 'Sleeve'],
    subtypes: ['dress', 'blouse', 'top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic', 'resort', 'minimal', 'bohemian'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'cotton-chambray',
    name: 'Cotton chambray',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body', 'Sleeve'],
    subtypes: ['shirt', 'dress', 'blouse', 'short'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['workwear', 'resort', 'preppy'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'cotton-jersey-light',
    name: 'Cotton jersey (lightweight)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 120, max: 180, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['tshirt', 'top', 'dress', 'loungewear', 'lingerie'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal', 'sport', 'streetwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-jersey-heavy',
    name: 'Cotton jersey (heavyweight)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 220, max: 320, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body'],
    subtypes: ['tshirt', 'loungewear', 'sweater'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'minimal', 'workwear'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'cotton-french-terry',
    name: 'Cotton french terry',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 240, max: 360, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['sweater', 'loungewear', 'activewear'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'streetwear', 'loungewear'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'cotton-fleece',
    name: 'Cotton fleece (loop-back / brushed)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 450, unit: 'gsm' },
    defaultFinish: 'brushed',
    zones: ['Body'],
    subtypes: ['sweater', 'loungewear', 'activewear'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'streetwear', 'loungewear'],
    seasonFit: ['FW'],
    vegan: true,
  },
  {
    id: 'cotton-pique',
    name: 'Cotton piqué',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 180, max: 240, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body'],
    subtypes: ['polo', 'dress', 'top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['preppy', 'sport', 'tailored'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'cotton-canvas',
    name: 'Cotton canvas (duck)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 450, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body', 'Pocket'],
    subtypes: ['outerwear-jacket', 'outerwear-coat', 'trouser', 'short'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'streetwear'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'cotton-corduroy',
    name: 'Cotton corduroy',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 400, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body'],
    subtypes: ['trouser', 'outerwear-jacket', 'blazer', 'skirt', 'short'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['workwear', 'preppy', 'tailored'],
    seasonFit: ['FW', 'transitional'],
    vegan: true,
  },
  {
    id: 'cotton-velvet',
    name: 'Cotton velvet',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 380, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['blazer', 'outerwear-jacket', 'dress', 'trouser', 'skirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'tailored', 'avant-garde'],
    seasonFit: ['FW'],
    vegan: true,
  },
  {
    id: 'cotton-flannel',
    name: 'Cotton flannel (brushed)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'brushed',
    zones: ['Body'],
    subtypes: ['shirt', 'loungewear'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'preppy'],
    seasonFit: ['FW', 'transitional'],
    vegan: true,
  },
  {
    id: 'cotton-denim',
    name: 'Cotton denim',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 480, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'stonewashed', 'enzyme-washed', 'laser-faded', 'selvedge'],
    zones: ['Body'],
    subtypes: ['jean', 'outerwear-jacket', 'skirt', 'short', 'dress'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'workwear', 'utility'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-organic',
    name: 'Organic cotton',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% organic cotton',
    weightRange: { min: 80, max: 450, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['tshirt', 'shirt', 'dress', 'top', 'loungewear', 'lingerie', 'trouser'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['sustainable', 'minimal', 'resort'],
    seasonFit: ['all-year'],
    certifications: ['GOTS', 'Organic-Content-Standard', 'OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'cotton-bci',
    name: 'BCI cotton (Better Cotton)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (BCI)',
    weightRange: { min: 80, max: 450, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['tshirt', 'shirt', 'trouser', 'jean'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sustainable', 'streetwear', 'workwear'],
    seasonFit: ['all-year'],
    certifications: ['BCI'],
    vegan: true,
  },
  {
    id: 'cotton-recycled',
    name: 'Recycled cotton',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '≥20% recycled cotton (often blended)',
    weightRange: { min: 130, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['tshirt', 'jean', 'sweater', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'streetwear', 'workwear'],
    seasonFit: ['all-year'],
    certifications: ['GRS', 'RCS'],
    vegan: true,
  },
  {
    id: 'cotton-supima',
    name: 'Supima / Pima cotton',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% Supima cotton',
    weightRange: { min: 90, max: 220, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body'],
    subtypes: ['tshirt', 'polo', 'shirt', 'blouse', 'loungewear', 'lingerie'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'preppy', 'tailored'],
    seasonFit: ['all-year'],
    certifications: ['Supima'],
    vegan: true,
  },
  {
    id: 'cotton-sea-island',
    name: 'Sea Island cotton',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% West Indian Sea Island cotton (WISICA-certified)',
    weightRange: { min: 90, max: 160, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body'],
    subtypes: ['shirt', 'blouse', 'tshirt', 'polo'],
    priceTier: ['luxury'],
    aestheticTags: ['minimal', 'tailored', 'preppy'],
    seasonFit: ['all-year'],
    certifications: ['WISICA'],
    vegan: true,
  },

  // ─── L3 — Verified B2B mill suppliers ───
  {
    id: 'supplier-albini',
    name: 'Cotonificio Albini / Albini Group',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (mill range)',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Italy (Bergamo)',
      tier: 'mill',
      verificationUrl: 'https://www.albinigroup.com/en/',
      secondaryUrl: 'https://tissura.com/manufacturers/cotonificio-albini',
    },
    notes: 'Largest European shirting manufacturer; family-run since 1876; 7 European factories; 20,000+ fabrics. Supplies Zegna, J.Crew and many others as a true B2B mill. Owns Thomas Mason, David & John Anderson, Albiate 1830. Holds exclusive rights to 100% of Sea Island cotton in Barbados and 90% in Jamaica.',
  },
  {
    id: 'supplier-thomas-mason',
    name: 'Thomas Mason (Albini Group)',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (heritage shirting range)',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Italy / UK heritage',
      tier: 'mill',
      verificationUrl: 'https://www.albinigroup.com/en/',
      secondaryUrl: 'https://www.permanentstyle.com/2017/05/shirting-mills-and-brands-explained.html',
    },
    notes: 'Heritage shirting brand inside Albini Group, retains UK heritage archive, sells fabrics under its own name to bespoke and ready-to-wear shirtmakers.',
  },
  {
    id: 'supplier-pontoglio',
    name: 'Pontoglio 1883',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (velvet & corduroy specialist)',
    zones: ['Body'],
    subtypes: ['blazer', 'trouser', 'outerwear-jacket', 'skirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'romantic'],
    seasonFit: ['FW'],
    vegan: true,
    supplier: {
      origin: 'Italy (Pontoglio, Brescia)',
      tier: 'mill',
      verificationUrl: 'https://suitsupply.com/en-us/journal/pontoglio-mill.html',
      secondaryUrl: 'https://www.europages.co.uk/companies/italy/velvet%20fabrics.html',
    },
    notes: '140+ year cotton velvet & corduroy specialist on the banks of the Oglio river; 63 weavers; sold globally as B2B fabrics through distributors and direct.',
  },
  {
    id: 'supplier-candiani',
    name: 'Candiani Denim',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (denim specialist; rigid/stretch/selvedge)',
    zones: ['Body'],
    subtypes: ['jean', 'outerwear-jacket', 'skirt'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'workwear'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Italy (Robecchetto con Induno, Milano)',
      tier: 'mill',
      verificationUrl: 'https://www.candianidenim.com/en',
      secondaryUrl: 'https://suitsupply.com/en-us/journal/candiani-mill.html',
    },
    notes: "Europe's largest denim mill since 1938; vertically integrated; B2B-only mill selling rigid/stretch/selvedge denim to many brands worldwide; 20M+ meters/year, 300 variations.",
  },
  {
    id: 'supplier-pozzi-electa',
    name: 'Pozzi Electa',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton yarn',
    zones: ['Body'],
    subtypes: ['tshirt', 'sweater', 'shirt'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['minimal', 'tailored'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Italy',
      tier: 'mill',
      verificationUrl: 'https://www.pozzielecta.it/en/about-us/',
      secondaryUrl: 'https://www.europages.co.uk/companies/italy/manufacturer%20producer/cotton-yarn.html',
    },
    notes: 'Italian cotton yarn manufacturer since 1889; B2B supplier listed on Europages and other professional B2B directories.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 2. LINEN / FLAX
// ═══════════════════════════════════════════════════════════════════════

const linen: Material[] = [
  {
    id: 'linen',
    name: 'Linen',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% linen (flax)',
    weightRange: { min: 80, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'stonewashed', 'garment-washed', 'softened', 'enzyme-washed'],
    zones: ['Body', 'Lining', 'Sleeve', 'Collar', 'Pocket'],
    subtypes: ['dress', 'top', 'shirt', 'blouse', 'trouser', 'short', 'skirt', 'jumpsuit', 'blazer', 'suit', 'outerwear-jacket'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['resort', 'minimal', 'romantic', 'tailored', 'sustainable', 'bohemian', 'preppy'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['OEKO-TEX', 'European-Flax', 'Masters-of-Linen', 'GOTS'],
    vegan: true,
  },
  {
    id: 'linen-voile',
    name: 'Linen voile (lightweight)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 80, max: 130, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body', 'Sleeve'],
    subtypes: ['blouse', 'dress', 'top', 'shirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['resort', 'romantic', 'minimal'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'linen-shirting',
    name: 'Linen shirting (light to mid)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body', 'Sleeve'],
    subtypes: ['shirt', 'dress', 'blouse', 'skirt'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['resort', 'minimal', 'tailored', 'preppy'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-midweight',
    name: 'Linen midweight',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 180, max: 240, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['trouser', 'skirt', 'short', 'dress', 'jumpsuit', 'blazer'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['resort', 'tailored', 'minimal'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-suiting',
    name: 'Linen suiting',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 200, max: 300, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'resort', 'minimal'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-canvas',
    name: 'Linen canvas (heavy)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 280, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'outerwear-coat', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['workwear', 'utility', 'tailored'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'linen-jersey',
    name: 'Linen jersey (knit)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen (knit)',
    weightRange: { min: 160, max: 220, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'top', 'dress', 'loungewear'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['resort', 'minimal', 'loungewear'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-slub',
    name: 'Slub linen',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'blazer', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'bohemian', 'minimal'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'linen-stonewashed',
    name: 'Stonewashed linen',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'stonewashed',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blouse', 'loungewear'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['resort', 'bohemian', 'loungewear', 'romantic'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-cotton-blend',
    name: 'Linen-cotton blend (50/50)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '55% linen 45% cotton (typical)',
    weightRange: { min: 130, max: 240, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'short', 'skirt', 'trouser', 'blazer'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['resort', 'preppy', 'tailored'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-damask',
    name: 'Linen damask (jacquard)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 200, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['dress', 'blouse', 'skirt'],
    priceTier: ['luxury'],
    aestheticTags: ['romantic', 'avant-garde'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-belgian',
    name: 'Belgian linen (PGI)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% Belgian linen (Belgian Linen™ trademark)',
    weightRange: { min: 130, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blazer', 'jumpsuit'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored', 'resort'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['Belgian-Linen', 'Masters-of-Linen'],
    vegan: true,
  },
  {
    id: 'linen-french-flax',
    name: 'French Flax linen (European Flax)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% French / European linen',
    weightRange: { min: 130, max: 320, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blazer', 'loungewear'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'romantic', 'resort'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['European-Flax', 'Masters-of-Linen'],
    vegan: true,
  },
  // L3 Linen suppliers
  {
    id: 'supplier-solbiati',
    name: 'Solbiati (Loro Piana Group, B2B division)',
    layer: 'L3',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen (mill range)',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blazer', 'suit'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored', 'resort'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
    supplier: {
      origin: 'Italy (Busto Arsizio)',
      tier: 'mill',
      verificationUrl: 'https://www.solbiati.it/en/home.html',
      secondaryUrl: 'https://www.joelandsonfabrics.com/collections/men-brands-solbiati-linen-cotton',
    },
    notes: 'Founded 1874; widely regarded as the leading Italian linen mill; selects European flax, weaves and finishes in Italy; sells under its own name to multiple bespoke tailors and brands as B2B. Owned by Loro Piana since 2013 but operates independently as a B2B fabric mill.',
  },
  {
    id: 'supplier-libeco',
    name: 'Libeco',
    layer: 'L3',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% Belgian linen',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'resort'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['Belgian-Linen', 'European-Flax'],
    vegan: true,
    supplier: {
      origin: 'Belgium (Meulebeke)',
      tier: 'mill',
      verificationUrl: 'https://www.libeco.com/en',
      secondaryUrl: 'https://en.wikipedia.org/wiki/Libeco',
    },
    notes: '6th-generation Belgian linen mill since 1858; produces European Flax Belgian Linen™ for apparel, upholstery, and home; bi-annual collections; B2B sales through agent network and digital ordering platform. Holds Belgian Linen™ certification authority.',
  },
  {
    id: 'supplier-tuscarora-mills',
    name: 'Tuscarora Mills',
    layer: 'L3',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: 'linen / organic cotton / hemp (B2B mill range)',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'resort', 'minimal'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
    supplier: {
      origin: 'USA (Bedford, Pennsylvania)',
      tier: 'mill',
      verificationUrl: 'https://tuscaroramills.com/',
    },
    notes: 'American-made linen, organic cotton, hemp; B2B mill targeting US designers and apparel brands; operates as supplier (not DTC).',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 3. HEMP
// ═══════════════════════════════════════════════════════════════════════

const hemp: Material[] = [
  {
    id: 'hemp',
    name: 'Hemp',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% hemp',
    weightRange: { min: 130, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened', 'stonewashed', 'enzyme-washed'],
    zones: ['Body', 'Pocket', 'Lining'],
    subtypes: ['shirt', 'trouser', 'short', 'outerwear-jacket', 'skirt', 'tshirt', 'dress'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'workwear', 'utility', 'resort', 'bohemian'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'hemp-shirting',
    name: 'Hemp shirting',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '100% hemp',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'resort', 'bohemian'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'hemp-canvas',
    name: 'Hemp canvas',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '100% hemp',
    weightRange: { min: 280, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'trouser', 'short'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'sustainable'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'hemp-cotton-blend',
    name: 'Hemp-cotton blend (55/45)',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '55% hemp 45% cotton (typical)',
    weightRange: { min: 160, max: 280, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'shirt', 'trouser', 'short', 'skirt'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'resort', 'streetwear'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'hemp-jersey',
    name: 'Hemp jersey',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '55% hemp 45% organic cotton',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'top', 'loungewear'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'loungewear', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'hemp-twill',
    name: 'Hemp twill',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '100% hemp',
    weightRange: { min: 200, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['trouser', 'short', 'outerwear-jacket'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'sustainable'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  // L3 Hemp suppliers
  {
    id: 'supplier-hemp-fortex',
    name: 'Hemp Fortex',
    layer: 'L3',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: 'hemp + hemp blends (vertically integrated)',
    zones: ['Body'],
    subtypes: ['tshirt', 'shirt', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'workwear'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['GOTS', 'OEKO-TEX'],
    vegan: true,
    supplier: {
      origin: 'China (vertically integrated)',
      tier: 'mill',
      verificationUrl: 'https://www.hempfortex.com/',
    },
    notes: 'Founded 1999; vertically integrated hemp mill (seed to garment); documented B2B sustainable hemp supplier serving multiple international brands. GOTS certified for blends.',
  },
  {
    id: 'supplier-envirotextiles',
    name: 'EnviroTextiles LLC',
    layer: 'L3',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: 'hemp + hemp blends (yarn + fabric)',
    zones: ['Body'],
    subtypes: ['shirt', 'trouser', 'tshirt'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'workwear'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
    supplier: {
      origin: 'USA (Glenwood Springs, Colorado)',
      tier: 'mill',
      verificationUrl: 'https://www.envirotextiles.com/',
    },
    notes: 'Designs, develops, imports and distributes hemp + hemp-blend yarns and fabrics; B2B-only natural fiber supplier.',
  },
  {
    id: 'supplier-tuscarora-mills-hemp',
    name: 'Tuscarora Mills (hemp line)',
    layer: 'L3',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: 'hemp / linen / organic cotton',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'resort'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
    supplier: {
      origin: 'USA (Bedford, Pennsylvania)',
      tier: 'mill',
      verificationUrl: 'https://tuscaroramills.com/',
    },
    notes: 'American-made hemp, linen, organic cotton; B2B mill for US apparel & home goods designers.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 4. RAMIE
// ═══════════════════════════════════════════════════════════════════════

const ramie: Material[] = [
  {
    id: 'ramie',
    name: 'Ramie',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% ramie',
    weightRange: { min: 130, max: 280, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened', 'mercerized'],
    zones: ['Body', 'Sleeve', 'Lining'],
    subtypes: ['shirt', 'blouse', 'dress', 'trouser', 'skirt', 'jumpsuit'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'minimal', 'sustainable', 'bohemian'],
    seasonFit: ['SS'],
    certifications: ['OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'ramie-shirting',
    name: 'Ramie shirting',
    layer: 'L2',
    parentId: 'ramie',
    family: 'natural-cellulosic',
    composition: '100% ramie',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'minimal'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'ramie-cotton-blend',
    name: 'Ramie-cotton blend',
    layer: 'L2',
    parentId: 'ramie',
    family: 'natural-cellulosic',
    composition: '55% ramie 45% cotton',
    weightRange: { min: 130, max: 220, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'skirt'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'bohemian', 'sustainable'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'ramie-linen-blend',
    name: 'Ramie-linen blend',
    layer: 'L2',
    parentId: 'ramie',
    family: 'natural-cellulosic',
    composition: '55% ramie 45% linen',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blazer'],
    priceTier: ['premium'],
    aestheticTags: ['resort', 'minimal', 'tailored'],
    seasonFit: ['SS'],
    vegan: true,
  },
  // L3 Ramie suppliers
  {
    id: 'supplier-ryoma',
    name: 'Ryoma (Ramie Fabric)',
    layer: 'L3',
    parentId: 'ramie',
    family: 'natural-cellulosic',
    composition: '100% ramie + blends',
    zones: ['Body'],
    subtypes: ['shirt', 'dress'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'sustainable'],
    seasonFit: ['SS'],
    vegan: true,
    supplier: {
      origin: 'China',
      tier: 'mill',
      verificationUrl: 'https://ramiefabric.com/',
    },
    notes: 'Specialised ramie mill marketing globally as a B2B supplier with custom bulk production and consultation. One of the few dedicated ramie B2B mills.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 5. JUTE
// ═══════════════════════════════════════════════════════════════════════

const jute: Material[] = [
  {
    id: 'jute',
    name: 'Jute',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% jute',
    weightRange: { min: 200, max: 600, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened', 'laminated'],
    zones: ['Body', 'Pocket'],
    subtypes: ['outerwear-jacket', 'skirt', 'short'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['sustainable', 'utility', 'bohemian', 'resort', 'workwear'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'jute-hessian',
    name: 'Jute hessian / burlap',
    layer: 'L2',
    parentId: 'jute',
    family: 'natural-cellulosic',
    composition: '100% jute',
    weightRange: { min: 200, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'short'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['bohemian', 'utility', 'resort'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'jute-cotton-blend',
    name: 'Jute-cotton blend',
    layer: 'L2',
    parentId: 'jute',
    family: 'natural-cellulosic',
    composition: '70% jute 30% cotton',
    weightRange: { min: 220, max: 360, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['short', 'skirt', 'outerwear-jacket'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['sustainable', 'utility', 'resort'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  // L3 Jute suppliers
  {
    id: 'supplier-fiberregion',
    name: 'FiberRegion',
    layer: 'L3',
    parentId: 'jute',
    family: 'natural-cellulosic',
    composition: 'raw jute, ramie, kenaf, pineapple, bamboo',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'short'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['sustainable', 'utility'],
    seasonFit: ['SS'],
    vegan: true,
    supplier: {
      origin: 'India (Chennai)',
      tier: 'mill',
      verificationUrl: 'https://www.fiberregion.in/natural-fibers.html',
    },
    notes: 'Wholesale trader of raw jute, ramie, kenaf, pineapple and bamboo natural fibers. B2B raw material supplier (not DTC).',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// REMAINING FIBERS — added in subsequent commits:
//   6. Bamboo                 (881-961)
//   7. Abaca                  (962-1030)
//   8. Piña                   (1031-1109)
//   9. Kapok                  (1110-1166, no L3)
//  10. Nettle                 (1167-1222, no L3)
//  11. Wool (sheep)           (1224-1516)
//  12. Cashmere               (1517-1673)
//  13. Mohair                 (1674-1791)
//  14. Alpaca                 (1792-1920)
//  15. Angora                 (1921-2017)
//  16. Vicuña                 (2018-2094)
//  17. Llama                  (2095-2161)
//  18. Camel hair             (2162-2251)
//  19. Yak                    (2252-2317)
//  20. Qiviut                 (2318-2396)
//  21. Silk                   (2397-2692)
// ═══════════════════════════════════════════════════════════════════════

// ─── Aggregate ─────────────────────────────────────────────────────────────

export const rama1: Material[] = [
  ...cotton,
  ...linen,
  ...hemp,
  ...ramie,
  ...jute,
  // ...bamboo, ...abaca, ...pina, ...kapok, ...nettle,
  // ...wool, ...cashmere, ...mohair, ...alpaca, ...angora, ...vicuna,
  // ...llama, ...camelHair, ...yak, ...qiviut, ...silk,
];
