/**
 * Rama 1 — Natural textile fibers
 *
 * Source: .research/materials-rama-1-natural-fibers.md (R2 cleanup applied
 * 2026-05-04 per Felipe's "si no está claro, fuera" rule).
 *
 * Coverage: 21 fibers (10 cellulosic + 11 animal).
 *   Cellulosic: cotton, linen, hemp, ramie, jute, bamboo, abaca, piña, kapok, nettle
 *   Animal:     wool, cashmere, mohair, alpaca, angora, vicuña, llama, camel hair, yak, qiviut, silk
 *
 * Layer counts:
 *   L1: 21 base entries
 *   L2: 92 construction × weight × finish variants
 *   L3: 47 verified B2B mill suppliers
 *   ───────
 *   Total: ~160 entries
 *
 * Entry order: by fiber section (matches markdown). Within fiber: L1 → L2 → L3.
 */

import type { Material } from './types';

// ═══════════════════════════════════════════════════════════════════════
// 1. COTTON
// ═══════════════════════════════════════════════════════════════════════

const cotton: Material[] = [
  // ─── L1 ───
  {
    id: 'cotton',
    name: 'Cotton',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 80, max: 450, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'sanforized', 'mercerized', 'garment-washed', 'stonewashed', 'brushed', 'peached', 'enzyme-washed', 'resin-finished'],
    zones: ['Body', 'Lining', 'Collar', 'Cuff', 'Pocket', 'Sleeve'],
    subtypes: ['dress', 'top', 'shirt', 'blouse', 'tshirt', 'polo', 'bottom', 'trouser', 'jean', 'short', 'skirt', 'jumpsuit', 'outerwear-jacket', 'blazer', 'suit', 'lingerie', 'loungewear', 'activewear'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored', 'streetwear', 'workwear', 'preppy', 'sport', 'sustainable', 'utility', 'resort'],
    seasonFit: ['SS', 'FW', 'transitional', 'all-year'],
    certifications: ['OEKO-TEX', 'GOTS', 'BCI', 'Organic-Content-Standard', 'Fair-Trade', 'Cradle-to-Cradle'],
    vegan: true,
  },

  // ─── L2 — Construction × weight × finish ───
  {
    id: 'cotton-poplin',
    name: 'Cotton poplin',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 90, max: 130, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored', 'preppy'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-twill',
    name: 'Cotton twill',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 180, max: 320, unit: 'gsm' },
    defaultFinish: 'sanforized',
    zones: ['Body', 'Sleeve', 'Pocket'],
    subtypes: ['trouser', 'short', 'outerwear-jacket', 'skirt', 'shirt'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'tailored', 'preppy'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'cotton-oxford',
    name: 'Cotton oxford',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt', 'blouse'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['preppy', 'tailored', 'workwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-pinpoint-oxford',
    name: 'Pinpoint oxford',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 110, max: 150, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-voile',
    name: 'Cotton voile',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 60, max: 100, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body', 'Sleeve'],
    subtypes: ['dress', 'blouse', 'top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['romantic', 'resort', 'minimal', 'bohemian'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'cotton-chambray',
    name: 'Cotton chambray',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body', 'Sleeve'],
    subtypes: ['shirt', 'dress', 'blouse', 'short'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['workwear', 'resort', 'preppy'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'cotton-jersey-light',
    name: 'Cotton jersey (lightweight)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 120, max: 180, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['tshirt', 'top', 'dress', 'loungewear', 'lingerie'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal', 'sport', 'streetwear'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-jersey-heavy',
    name: 'Cotton jersey (heavyweight)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 220, max: 320, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body'],
    subtypes: ['tshirt', 'loungewear', 'sweater'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'minimal', 'workwear'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'cotton-french-terry',
    name: 'Cotton french terry',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 240, max: 360, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['sweater', 'loungewear', 'activewear'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'streetwear', 'loungewear'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'cotton-fleece',
    name: 'Cotton fleece (loop-back / brushed)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 450, unit: 'gsm' },
    defaultFinish: 'brushed',
    zones: ['Body'],
    subtypes: ['sweater', 'loungewear', 'activewear'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sport', 'streetwear', 'loungewear'],
    seasonFit: ['FW'],
    vegan: true,
  },
  {
    id: 'cotton-pique',
    name: 'Cotton piqué',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 180, max: 240, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body'],
    subtypes: ['polo', 'dress', 'top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['preppy', 'sport', 'tailored'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'cotton-canvas',
    name: 'Cotton canvas (duck)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 450, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body', 'Pocket'],
    subtypes: ['outerwear-jacket', 'outerwear-coat', 'trouser', 'short'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'streetwear'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'cotton-corduroy',
    name: 'Cotton corduroy',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 400, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body'],
    subtypes: ['trouser', 'outerwear-jacket', 'blazer', 'skirt', 'short'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['workwear', 'preppy', 'tailored'],
    seasonFit: ['FW', 'transitional'],
    vegan: true,
  },
  {
    id: 'cotton-velvet',
    name: 'Cotton velvet',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 380, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['blazer', 'outerwear-jacket', 'dress', 'trouser', 'skirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['romantic', 'tailored', 'avant-garde'],
    seasonFit: ['FW'],
    vegan: true,
  },
  {
    id: 'cotton-flannel',
    name: 'Cotton flannel (brushed)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'brushed',
    zones: ['Body'],
    subtypes: ['shirt', 'loungewear'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'preppy'],
    seasonFit: ['FW', 'transitional'],
    vegan: true,
  },
  {
    id: 'cotton-denim',
    name: 'Cotton denim',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton',
    weightRange: { min: 280, max: 480, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'stonewashed', 'enzyme-washed', 'laser-faded', 'selvedge'],
    zones: ['Body'],
    subtypes: ['jean', 'outerwear-jacket', 'skirt', 'short', 'dress'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'workwear', 'utility'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'cotton-organic',
    name: 'Organic cotton',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% organic cotton',
    weightRange: { min: 80, max: 450, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['tshirt', 'shirt', 'dress', 'top', 'loungewear', 'lingerie', 'trouser'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['sustainable', 'minimal', 'resort'],
    seasonFit: ['all-year'],
    certifications: ['GOTS', 'Organic-Content-Standard', 'OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'cotton-bci',
    name: 'BCI cotton (Better Cotton)',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (BCI)',
    weightRange: { min: 80, max: 450, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['tshirt', 'shirt', 'trouser', 'jean'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sustainable', 'streetwear', 'workwear'],
    seasonFit: ['all-year'],
    certifications: ['BCI'],
    vegan: true,
  },
  {
    id: 'cotton-recycled',
    name: 'Recycled cotton',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '≥20% recycled cotton (often blended)',
    weightRange: { min: 130, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['tshirt', 'jean', 'sweater', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'streetwear', 'workwear'],
    seasonFit: ['all-year'],
    certifications: ['GRS', 'RCS'],
    vegan: true,
  },
  {
    id: 'cotton-supima',
    name: 'Supima / Pima cotton',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% Supima cotton',
    weightRange: { min: 90, max: 220, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body'],
    subtypes: ['tshirt', 'polo', 'shirt', 'blouse', 'loungewear', 'lingerie'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'preppy', 'tailored'],
    seasonFit: ['all-year'],
    certifications: ['Supima'],
    vegan: true,
  },
  {
    id: 'cotton-sea-island',
    name: 'Sea Island cotton',
    layer: 'L2',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% West Indian Sea Island cotton (WISICA-certified)',
    weightRange: { min: 90, max: 160, unit: 'gsm' },
    defaultFinish: 'mercerized',
    zones: ['Body'],
    subtypes: ['shirt', 'blouse', 'tshirt', 'polo'],
    priceTier: ['luxury'],
    aestheticTags: ['minimal', 'tailored', 'preppy'],
    seasonFit: ['all-year'],
    certifications: ['WISICA'],
    vegan: true,
  },

  // ─── L3 — Verified B2B mill suppliers ───
  {
    id: 'supplier-albini',
    name: 'Cotonificio Albini / Albini Group',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (mill range)',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Italy (Bergamo)',
      tier: 'mill',
      verificationUrl: 'https://www.albinigroup.com/en/',
      secondaryUrl: 'https://tissura.com/manufacturers/cotonificio-albini',
    },
    notes: 'Largest European shirting manufacturer; family-run since 1876; 7 European factories; 20,000+ fabrics. Supplies Zegna, J.Crew and many others as a true B2B mill. Owns Thomas Mason, David & John Anderson, Albiate 1830. Holds exclusive rights to 100% of Sea Island cotton in Barbados and 90% in Jamaica.',
  },
  {
    id: 'supplier-thomas-mason',
    name: 'Thomas Mason (Albini Group)',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (heritage shirting range)',
    zones: ['Body', 'Sleeve', 'Collar'],
    subtypes: ['shirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Italy / UK heritage',
      tier: 'mill',
      verificationUrl: 'https://www.albinigroup.com/en/',
      secondaryUrl: 'https://www.permanentstyle.com/2017/05/shirting-mills-and-brands-explained.html',
    },
    notes: 'Heritage shirting brand inside Albini Group, retains UK heritage archive, sells fabrics under its own name to bespoke and ready-to-wear shirtmakers.',
  },
  {
    id: 'supplier-pontoglio',
    name: 'Pontoglio 1883',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (velvet & corduroy specialist)',
    zones: ['Body'],
    subtypes: ['blazer', 'trouser', 'outerwear-jacket', 'skirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'romantic'],
    seasonFit: ['FW'],
    vegan: true,
    supplier: {
      origin: 'Italy (Pontoglio, Brescia)',
      tier: 'mill',
      verificationUrl: 'https://suitsupply.com/en-us/journal/pontoglio-mill.html',
      secondaryUrl: 'https://www.europages.co.uk/companies/italy/velvet%20fabrics.html',
    },
    notes: '140+ year cotton velvet & corduroy specialist on the banks of the Oglio river; 63 weavers; sold globally as B2B fabrics through distributors and direct.',
  },
  {
    id: 'supplier-candiani',
    name: 'Candiani Denim',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton (denim specialist; rigid/stretch/selvedge)',
    zones: ['Body'],
    subtypes: ['jean', 'outerwear-jacket', 'skirt'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['streetwear', 'workwear'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Italy (Robecchetto con Induno, Milano)',
      tier: 'mill',
      verificationUrl: 'https://www.candianidenim.com/en',
      secondaryUrl: 'https://suitsupply.com/en-us/journal/candiani-mill.html',
    },
    notes: "Europe's largest denim mill since 1938; vertically integrated; B2B-only mill selling rigid/stretch/selvedge denim to many brands worldwide; 20M+ meters/year, 300 variations.",
  },
  {
    id: 'supplier-pozzi-electa',
    name: 'Pozzi Electa',
    layer: 'L3',
    parentId: 'cotton',
    family: 'natural-cellulosic',
    composition: '100% cotton yarn',
    zones: ['Body'],
    subtypes: ['tshirt', 'sweater', 'shirt'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['minimal', 'tailored'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'Italy',
      tier: 'mill',
      verificationUrl: 'https://www.pozzielecta.it/en/about-us/',
      secondaryUrl: 'https://www.europages.co.uk/companies/italy/manufacturer%20producer/cotton-yarn.html',
    },
    notes: 'Italian cotton yarn manufacturer since 1889; B2B supplier listed on Europages and other professional B2B directories.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 2. LINEN / FLAX
// ═══════════════════════════════════════════════════════════════════════

const linen: Material[] = [
  {
    id: 'linen',
    name: 'Linen',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% linen (flax)',
    weightRange: { min: 80, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'stonewashed', 'garment-washed', 'softened', 'enzyme-washed'],
    zones: ['Body', 'Lining', 'Sleeve', 'Collar', 'Pocket'],
    subtypes: ['dress', 'top', 'shirt', 'blouse', 'trouser', 'short', 'skirt', 'jumpsuit', 'blazer', 'suit', 'outerwear-jacket'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['resort', 'minimal', 'romantic', 'tailored', 'sustainable', 'bohemian', 'preppy'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['OEKO-TEX', 'European-Flax', 'Masters-of-Linen', 'GOTS'],
    vegan: true,
  },
  {
    id: 'linen-voile',
    name: 'Linen voile (lightweight)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 80, max: 130, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body', 'Sleeve'],
    subtypes: ['blouse', 'dress', 'top', 'shirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['resort', 'romantic', 'minimal'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'linen-shirting',
    name: 'Linen shirting (light to mid)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body', 'Sleeve'],
    subtypes: ['shirt', 'dress', 'blouse', 'skirt'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['resort', 'minimal', 'tailored', 'preppy'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-midweight',
    name: 'Linen midweight',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 180, max: 240, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['trouser', 'skirt', 'short', 'dress', 'jumpsuit', 'blazer'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['resort', 'tailored', 'minimal'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-suiting',
    name: 'Linen suiting',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 200, max: 300, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'resort', 'minimal'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-canvas',
    name: 'Linen canvas (heavy)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 280, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'outerwear-coat', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['workwear', 'utility', 'tailored'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'linen-jersey',
    name: 'Linen jersey (knit)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen (knit)',
    weightRange: { min: 160, max: 220, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'top', 'dress', 'loungewear'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['resort', 'minimal', 'loungewear'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-slub',
    name: 'Slub linen',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'blazer', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'bohemian', 'minimal'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'linen-stonewashed',
    name: 'Stonewashed linen',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'stonewashed',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blouse', 'loungewear'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['resort', 'bohemian', 'loungewear', 'romantic'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-cotton-blend',
    name: 'Linen-cotton blend (50/50)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '55% linen 45% cotton (typical)',
    weightRange: { min: 130, max: 240, unit: 'gsm' },
    defaultFinish: 'garment-washed',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'short', 'skirt', 'trouser', 'blazer'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['resort', 'preppy', 'tailored'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-damask',
    name: 'Linen damask (jacquard)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen',
    weightRange: { min: 200, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['dress', 'blouse', 'skirt'],
    priceTier: ['luxury'],
    aestheticTags: ['romantic', 'avant-garde'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'linen-belgian',
    name: 'Belgian linen (PGI)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% Belgian linen (Belgian Linen™ trademark)',
    weightRange: { min: 130, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blazer', 'jumpsuit'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored', 'resort'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['Belgian-Linen', 'Masters-of-Linen'],
    vegan: true,
  },
  {
    id: 'linen-french-flax',
    name: 'French Flax linen (European Flax)',
    layer: 'L2',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% French / European linen',
    weightRange: { min: 130, max: 320, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blazer', 'loungewear'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'romantic', 'resort'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['European-Flax', 'Masters-of-Linen'],
    vegan: true,
  },
  // L3 Linen suppliers
  {
    id: 'supplier-solbiati',
    name: 'Solbiati (Loro Piana Group, B2B division)',
    layer: 'L3',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% linen (mill range)',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blazer', 'suit'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored', 'resort'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
    supplier: {
      origin: 'Italy (Busto Arsizio)',
      tier: 'mill',
      verificationUrl: 'https://www.solbiati.it/en/home.html',
      secondaryUrl: 'https://www.joelandsonfabrics.com/collections/men-brands-solbiati-linen-cotton',
    },
    notes: 'Founded 1874; widely regarded as the leading Italian linen mill; selects European flax, weaves and finishes in Italy; sells under its own name to multiple bespoke tailors and brands as B2B. Owned by Loro Piana since 2013 but operates independently as a B2B fabric mill.',
  },
  {
    id: 'supplier-libeco',
    name: 'Libeco',
    layer: 'L3',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: '100% Belgian linen',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['minimal', 'resort'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['Belgian-Linen', 'European-Flax'],
    vegan: true,
    supplier: {
      origin: 'Belgium (Meulebeke)',
      tier: 'mill',
      verificationUrl: 'https://www.libeco.com/en',
      secondaryUrl: 'https://en.wikipedia.org/wiki/Libeco',
    },
    notes: '6th-generation Belgian linen mill since 1858; produces European Flax Belgian Linen™ for apparel, upholstery, and home; bi-annual collections; B2B sales through agent network and digital ordering platform. Holds Belgian Linen™ certification authority.',
  },
  {
    id: 'supplier-tuscarora-mills',
    name: 'Tuscarora Mills',
    layer: 'L3',
    parentId: 'linen',
    family: 'natural-cellulosic',
    composition: 'linen / organic cotton / hemp (B2B mill range)',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'resort', 'minimal'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
    supplier: {
      origin: 'USA (Bedford, Pennsylvania)',
      tier: 'mill',
      verificationUrl: 'https://tuscaroramills.com/',
    },
    notes: 'American-made linen, organic cotton, hemp; B2B mill targeting US designers and apparel brands; operates as supplier (not DTC).',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 3. HEMP
// ═══════════════════════════════════════════════════════════════════════

const hemp: Material[] = [
  {
    id: 'hemp',
    name: 'Hemp',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% hemp',
    weightRange: { min: 130, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened', 'stonewashed', 'enzyme-washed'],
    zones: ['Body', 'Pocket', 'Lining'],
    subtypes: ['shirt', 'trouser', 'short', 'outerwear-jacket', 'skirt', 'tshirt', 'dress'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'workwear', 'utility', 'resort', 'bohemian'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'hemp-shirting',
    name: 'Hemp shirting',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '100% hemp',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'resort', 'bohemian'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'hemp-canvas',
    name: 'Hemp canvas',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '100% hemp',
    weightRange: { min: 280, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'trouser', 'short'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'sustainable'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  {
    id: 'hemp-cotton-blend',
    name: 'Hemp-cotton blend (55/45)',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '55% hemp 45% cotton (typical)',
    weightRange: { min: 160, max: 280, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'shirt', 'trouser', 'short', 'skirt'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'resort', 'streetwear'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  {
    id: 'hemp-jersey',
    name: 'Hemp jersey',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '55% hemp 45% organic cotton',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'top', 'loungewear'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'loungewear', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'hemp-twill',
    name: 'Hemp twill',
    layer: 'L2',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: '100% hemp',
    weightRange: { min: 200, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['trouser', 'short', 'outerwear-jacket'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['workwear', 'utility', 'sustainable'],
    seasonFit: ['transitional', 'FW'],
    vegan: true,
  },
  // L3 Hemp suppliers
  {
    id: 'supplier-hemp-fortex',
    name: 'Hemp Fortex',
    layer: 'L3',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: 'hemp + hemp blends (vertically integrated)',
    zones: ['Body'],
    subtypes: ['tshirt', 'shirt', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'workwear'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['GOTS', 'OEKO-TEX'],
    vegan: true,
    supplier: {
      origin: 'China (vertically integrated)',
      tier: 'mill',
      verificationUrl: 'https://www.hempfortex.com/',
    },
    notes: 'Founded 1999; vertically integrated hemp mill (seed to garment); documented B2B sustainable hemp supplier serving multiple international brands. GOTS certified for blends.',
  },
  {
    id: 'supplier-envirotextiles',
    name: 'EnviroTextiles LLC',
    layer: 'L3',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: 'hemp + hemp blends (yarn + fabric)',
    zones: ['Body'],
    subtypes: ['shirt', 'trouser', 'tshirt'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'workwear'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
    supplier: {
      origin: 'USA (Glenwood Springs, Colorado)',
      tier: 'mill',
      verificationUrl: 'https://www.envirotextiles.com/',
    },
    notes: 'Designs, develops, imports and distributes hemp + hemp-blend yarns and fabrics; B2B-only natural fiber supplier.',
  },
  {
    id: 'supplier-tuscarora-mills-hemp',
    name: 'Tuscarora Mills (hemp line)',
    layer: 'L3',
    parentId: 'hemp',
    family: 'natural-cellulosic',
    composition: 'hemp / linen / organic cotton',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'resort'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
    supplier: {
      origin: 'USA (Bedford, Pennsylvania)',
      tier: 'mill',
      verificationUrl: 'https://tuscaroramills.com/',
    },
    notes: 'American-made hemp, linen, organic cotton; B2B mill for US apparel & home goods designers.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 4. RAMIE
// ═══════════════════════════════════════════════════════════════════════

const ramie: Material[] = [
  {
    id: 'ramie',
    name: 'Ramie',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% ramie',
    weightRange: { min: 130, max: 280, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened', 'mercerized'],
    zones: ['Body', 'Sleeve', 'Lining'],
    subtypes: ['shirt', 'blouse', 'dress', 'trouser', 'skirt', 'jumpsuit'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'minimal', 'sustainable', 'bohemian'],
    seasonFit: ['SS'],
    certifications: ['OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'ramie-shirting',
    name: 'Ramie shirting',
    layer: 'L2',
    parentId: 'ramie',
    family: 'natural-cellulosic',
    composition: '100% ramie',
    weightRange: { min: 130, max: 180, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'minimal'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'ramie-cotton-blend',
    name: 'Ramie-cotton blend',
    layer: 'L2',
    parentId: 'ramie',
    family: 'natural-cellulosic',
    composition: '55% ramie 45% cotton',
    weightRange: { min: 130, max: 220, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'skirt'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'bohemian', 'sustainable'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'ramie-linen-blend',
    name: 'Ramie-linen blend',
    layer: 'L2',
    parentId: 'ramie',
    family: 'natural-cellulosic',
    composition: '55% ramie 45% linen',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser', 'blazer'],
    priceTier: ['premium'],
    aestheticTags: ['resort', 'minimal', 'tailored'],
    seasonFit: ['SS'],
    vegan: true,
  },
  // L3 Ramie suppliers
  {
    id: 'supplier-ryoma',
    name: 'Ryoma (Ramie Fabric)',
    layer: 'L3',
    parentId: 'ramie',
    family: 'natural-cellulosic',
    composition: '100% ramie + blends',
    zones: ['Body'],
    subtypes: ['shirt', 'dress'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['resort', 'sustainable'],
    seasonFit: ['SS'],
    vegan: true,
    supplier: {
      origin: 'China',
      tier: 'mill',
      verificationUrl: 'https://ramiefabric.com/',
    },
    notes: 'Specialised ramie mill marketing globally as a B2B supplier with custom bulk production and consultation. One of the few dedicated ramie B2B mills.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 5. JUTE
// ═══════════════════════════════════════════════════════════════════════

const jute: Material[] = [
  {
    id: 'jute',
    name: 'Jute',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% jute',
    weightRange: { min: 200, max: 600, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened', 'laminated'],
    zones: ['Body', 'Pocket'],
    subtypes: ['outerwear-jacket', 'skirt', 'short'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['sustainable', 'utility', 'bohemian', 'resort', 'workwear'],
    seasonFit: ['SS', 'transitional'],
    certifications: ['OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'jute-hessian',
    name: 'Jute hessian / burlap',
    layer: 'L2',
    parentId: 'jute',
    family: 'natural-cellulosic',
    composition: '100% jute',
    weightRange: { min: 200, max: 400, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'short'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['bohemian', 'utility', 'resort'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'jute-cotton-blend',
    name: 'Jute-cotton blend',
    layer: 'L2',
    parentId: 'jute',
    family: 'natural-cellulosic',
    composition: '70% jute 30% cotton',
    weightRange: { min: 220, max: 360, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['short', 'skirt', 'outerwear-jacket'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['sustainable', 'utility', 'resort'],
    seasonFit: ['SS', 'transitional'],
    vegan: true,
  },
  // L3 Jute suppliers
  {
    id: 'supplier-fiberregion',
    name: 'FiberRegion',
    layer: 'L3',
    parentId: 'jute',
    family: 'natural-cellulosic',
    composition: 'raw jute, ramie, kenaf, pineapple, bamboo',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'short'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['sustainable', 'utility'],
    seasonFit: ['SS'],
    vegan: true,
    supplier: {
      origin: 'India (Chennai)',
      tier: 'mill',
      verificationUrl: 'https://www.fiberregion.in/natural-fibers.html',
    },
    notes: 'Wholesale trader of raw jute, ramie, kenaf, pineapple and bamboo natural fibers. B2B raw material supplier (not DTC).',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 6. BAMBOO
// ═══════════════════════════════════════════════════════════════════════

const bamboo: Material[] = [
  {
    id: 'bamboo',
    name: 'Bamboo',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% bamboo (mechanical/linen-form) or bamboo viscose',
    weightRange: { min: 120, max: 300, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened', 'mercerized'],
    zones: ['Body', 'Lining'],
    subtypes: ['tshirt', 'shirt', 'loungewear', 'lingerie', 'dress'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['sustainable', 'minimal', 'loungewear', 'sport'],
    seasonFit: ['all-year'],
    certifications: ['OEKO-TEX', 'FSC'],
    vegan: true,
  },
  {
    id: 'bamboo-linen',
    name: 'Bamboo linen (mechanical)',
    layer: 'L2',
    parentId: 'bamboo',
    family: 'natural-cellulosic',
    composition: '100% bamboo (mechanically processed bast)',
    weightRange: { min: 130, max: 220, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['shirt', 'dress', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['sustainable', 'minimal', 'resort'],
    seasonFit: ['SS'],
    vegan: true,
    notes: 'True natural bamboo fiber (rare). Linen-like hand-feel.',
  },
  {
    id: 'bamboo-viscose',
    name: 'Bamboo viscose / rayon',
    layer: 'L2',
    parentId: 'bamboo',
    family: 'natural-cellulosic',
    composition: '100% bamboo viscose',
    weightRange: { min: 120, max: 240, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'loungewear', 'lingerie', 'dress'],
    priceTier: ['fast', 'contemporary', 'premium'],
    aestheticTags: ['loungewear', 'minimal', 'sport'],
    seasonFit: ['all-year'],
    vegan: true,
    notes: 'Chemically regenerated — technically a regenerated cellulosic. Flagged for transparency in catalog UI to avoid greenwashing.',
  },
  {
    id: 'bamboo-cotton-blend',
    name: 'Bamboo-cotton blend',
    layer: 'L2',
    parentId: 'bamboo',
    family: 'natural-cellulosic',
    composition: '70% bamboo viscose 30% cotton',
    weightRange: { min: 140, max: 220, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'loungewear', 'lingerie'],
    priceTier: ['fast', 'contemporary'],
    aestheticTags: ['loungewear', 'sport', 'minimal'],
    seasonFit: ['all-year'],
    vegan: true,
  },
  {
    id: 'supplier-proeco-organics',
    name: 'ProECO Organics',
    layer: 'L3',
    parentId: 'bamboo',
    family: 'natural-cellulosic',
    composition: 'bamboo + organic cotton blends',
    zones: ['Body'],
    subtypes: ['tshirt', 'loungewear'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'loungewear'],
    seasonFit: ['all-year'],
    vegan: true,
    supplier: {
      origin: 'USA (importer of bamboo viscose blends)',
      tier: 'mill',
      verificationUrl: 'https://proecofabrics.com/bamboo/',
    },
    notes: 'B2B distributor of bamboo and organic-cotton blend fabrics for the apparel market; supplies multiple US fashion brands.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 7. ABACÁ (Manila Hemp)
// ═══════════════════════════════════════════════════════════════════════

const abaca: Material[] = [
  {
    id: 'abaca',
    name: 'Abacá (Manila hemp)',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% abacá',
    weightRange: { min: 80, max: 200, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened'],
    zones: ['Body', 'Sleeve'],
    subtypes: ['dress', 'blouse', 'top'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['resort', 'bohemian', 'avant-garde', 'sustainable'],
    seasonFit: ['SS'],
    certifications: ['OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'abaca-sinamay',
    name: 'Sinamay (woven abacá)',
    layer: 'L2',
    parentId: 'abaca',
    family: 'natural-cellulosic',
    composition: '100% abacá',
    weightRange: { min: 60, max: 130, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['dress', 'blouse'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['avant-garde', 'bohemian', 'resort'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'abaca-silk-blend',
    name: 'Abacá-silk blend',
    layer: 'L2',
    parentId: 'abaca',
    family: 'natural-cellulosic',
    composition: '60% abacá 40% silk',
    weightRange: { min: 80, max: 160, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['dress', 'blouse'],
    priceTier: ['luxury'],
    aestheticTags: ['resort', 'romantic', 'bohemian'],
    seasonFit: ['SS'],
    vegan: false, // contains silk
  },
  {
    id: 'supplier-hermin-textile',
    name: 'HerMin Textile',
    layer: 'L3',
    parentId: 'abaca',
    family: 'natural-cellulosic',
    composition: '100% abacá fabrics',
    zones: ['Body'],
    subtypes: ['dress', 'blouse'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['resort', 'sustainable'],
    seasonFit: ['SS'],
    vegan: true,
    supplier: {
      origin: 'Taiwan (Philippines-sourced fiber)',
      tier: 'mill',
      verificationUrl: 'https://www.hermin.com/product-abaca-paper-fabric.html',
    },
    notes: 'B2B abacá fabric supplier explicitly serving apparel, footwear and furniture industries with biodegradable abacá textiles.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 8. PIÑA (Pineapple Leaf Fiber)
// ═══════════════════════════════════════════════════════════════════════

const pina: Material[] = [
  {
    id: 'pina',
    name: 'Piña (pineapple leaf fiber)',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% piña',
    weightRange: { min: 60, max: 140, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened'],
    zones: ['Body', 'Sleeve'],
    subtypes: ['dress', 'blouse', 'top'],
    priceTier: ['luxury'],
    aestheticTags: ['resort', 'romantic', 'bohemian', 'avant-garde', 'sustainable'],
    seasonFit: ['SS'],
    certifications: ['OEKO-TEX'],
    vegan: true,
  },
  {
    id: 'pina-seda',
    name: 'Piña Seda (piña-silk blend)',
    layer: 'L2',
    parentId: 'pina',
    family: 'natural-cellulosic',
    composition: '60% piña 40% silk',
    weightRange: { min: 80, max: 130, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['dress', 'blouse'],
    priceTier: ['luxury'],
    aestheticTags: ['romantic', 'resort', 'bohemian'],
    seasonFit: ['SS'],
    vegan: false, // contains silk
  },
  {
    id: 'pina-handwoven',
    name: 'Piña handwoven (traditional)',
    layer: 'L2',
    parentId: 'pina',
    family: 'natural-cellulosic',
    composition: '100% piña',
    weightRange: { min: 60, max: 110, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['dress', 'blouse'],
    priceTier: ['luxury'],
    aestheticTags: ['bohemian', 'resort', 'avant-garde'],
    seasonFit: ['SS'],
    vegan: true,
  },
  {
    id: 'supplier-anthill-fabrics',
    name: 'ANTHILL Fabrics',
    layer: 'L3',
    parentId: 'pina',
    family: 'natural-cellulosic',
    composition: 'piña / abacá / piña-seda blends',
    zones: ['Body'],
    subtypes: ['dress', 'blouse'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['resort', 'bohemian', 'sustainable'],
    seasonFit: ['SS'],
    vegan: true,
    supplier: {
      origin: 'Philippines (Cebu)',
      tier: 'mill',
      verificationUrl: 'https://anthillfabrics.com/products/abaca-silk-natural-copy',
    },
    notes: 'Social enterprise / B2B fabric studio working with traditional weaving communities; distributes piña, abacá, piña-seda blends to brands and designers globally.',
  },
  {
    id: 'supplier-handa-textiles',
    name: 'Handa Textiles',
    layer: 'L3',
    parentId: 'pina',
    family: 'natural-cellulosic',
    composition: 'piña handwoven / Filipino heritage fabrics',
    zones: ['Body'],
    subtypes: ['dress', 'blouse'],
    priceTier: ['luxury'],
    aestheticTags: ['bohemian', 'resort'],
    seasonFit: ['SS'],
    vegan: true,
    supplier: {
      origin: 'Philippines',
      tier: 'mill',
      verificationUrl: 'https://www.handatextiles.com/fabrics/p/pina-fabric',
    },
    notes: 'Traditional handwoven piña and Filipino heritage fabrics sold by the yard to designers and ateliers worldwide.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 9. KAPOK (no L3 — sourcing through fiber traders, not B2B mills)
// ═══════════════════════════════════════════════════════════════════════

const kapok: Material[] = [
  {
    id: 'kapok',
    name: 'Kapok',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% kapok (rare); usually blended',
    weightRange: { min: null, max: null, unit: null },
    defaultFinish: 'raw',
    zones: ['Lining', 'Padding (insulation)'],
    subtypes: ['outerwear-coat', 'outerwear-jacket', 'loungewear'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['sustainable', 'minimal'],
    seasonFit: ['FW', 'transitional'],
    certifications: ['OEKO-TEX'],
    vegan: true,
    notes: 'Kapok is typically used as a fill / insulation fiber, not woven on its own. Often blended into nonwoven padding (down alternative) or in low percentages with cotton.',
  },
  {
    id: 'kapok-padding',
    name: 'Kapok padding (down alternative)',
    layer: 'L2',
    parentId: 'kapok',
    family: 'natural-cellulosic',
    composition: '100% kapok fiber fill',
    weightRange: { min: null, max: null, unit: null },
    defaultFinish: 'raw',
    zones: ['Padding (insulation)'],
    subtypes: ['outerwear-coat', 'outerwear-jacket'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['sustainable', 'minimal'],
    seasonFit: ['FW'],
    vegan: true,
  },
  {
    id: 'kapok-cotton-blend',
    name: 'Kapok-cotton blend (woven)',
    layer: 'L2',
    parentId: 'kapok',
    family: 'natural-cellulosic',
    composition: '30% kapok 70% cotton (typical)',
    weightRange: { min: 160, max: 240, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['tshirt', 'loungewear'],
    priceTier: ['premium'],
    aestheticTags: ['sustainable', 'loungewear'],
    seasonFit: ['all-year'],
    vegan: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 10. NETTLE (no L3 — artisanal cooperative supply only)
// ═══════════════════════════════════════════════════════════════════════

const nettle: Material[] = [
  {
    id: 'nettle',
    name: 'Nettle (Allo)',
    layer: 'L1',
    family: 'natural-cellulosic',
    composition: '100% nettle (Himalayan / European)',
    weightRange: { min: 160, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'softened'],
    zones: ['Body', 'Pocket'],
    subtypes: ['shirt', 'outerwear-jacket', 'trouser', 'dress'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['sustainable', 'bohemian', 'minimal', 'avant-garde'],
    seasonFit: ['transitional', 'FW'],
    certifications: ['OEKO-TEX'],
    vegan: true,
    notes: 'Sourced via artisanal cooperatives in Nepal and northern Italy. No industrial B2B mill exists today.',
  },
  {
    id: 'nettle-shirting',
    name: 'Nettle shirting',
    layer: 'L2',
    parentId: 'nettle',
    family: 'natural-cellulosic',
    composition: '100% nettle',
    weightRange: { min: 160, max: 220, unit: 'gsm' },
    defaultFinish: 'softened',
    zones: ['Body'],
    subtypes: ['shirt', 'blouse', 'dress'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['sustainable', 'minimal', 'bohemian'],
    seasonFit: ['transitional'],
    vegan: true,
  },
  {
    id: 'nettle-canvas',
    name: 'Nettle canvas',
    layer: 'L2',
    parentId: 'nettle',
    family: 'natural-cellulosic',
    composition: '100% nettle',
    weightRange: { min: 240, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['outerwear-jacket', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['workwear', 'sustainable', 'avant-garde'],
    seasonFit: ['FW', 'transitional'],
    vegan: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════
// 11. WOOL (Sheep)
// ═══════════════════════════════════════════════════════════════════════

const wool: Material[] = [
  {
    id: 'wool',
    name: 'Wool (sheep)',
    layer: 'L1',
    family: 'natural-animal',
    composition: '100% wool',
    weightRange: { min: 170, max: 600, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['raw', 'fulled', 'milled', 'brushed', 'mercerized', 'Super-100s', 'Super-120s', 'Super-150s', 'Super-180s'],
    zones: ['Body', 'Lining', 'Sleeve', 'Collar', 'Cuff'],
    subtypes: ['sweater', 'knitwear-top', 'blazer', 'suit', 'trouser', 'outerwear-jacket', 'outerwear-coat', 'skirt', 'dress'],
    priceTier: ['fast', 'contemporary', 'premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy', 'minimal', 'workwear', 'sustainable', 'avant-garde'],
    seasonFit: ['FW', 'transitional'],
    certifications: ['RWS', 'OEKO-TEX', 'Woolmark', 'ZQ-Merino', 'NATIVA'],
    vegan: false,
  },
  {
    id: 'wool-merino',
    name: 'Merino wool',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% Merino wool',
    weightRange: { min: 130, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['sweater', 'knitwear-top', 'tshirt', 'activewear', 'loungewear', 'suit', 'blazer'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal', 'sport', 'tailored'],
    seasonFit: ['all-year'],
    certifications: ['RWS', 'Woolmark', 'ZQ-Merino', 'NATIVA'],
    vegan: false,
  },
  {
    id: 'wool-lambswool',
    name: 'Lambswool',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% lambswool (first-shear, ≤7 months)',
    weightRange: { min: 200, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['sweater', 'knitwear-top'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['preppy', 'tailored', 'minimal'],
    seasonFit: ['FW'],
    vegan: false,
  },
  {
    id: 'wool-virgin',
    name: 'Virgin wool',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% virgin wool',
    weightRange: { min: 200, max: 600, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser', 'outerwear-coat', 'outerwear-jacket', 'sweater'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy'],
    seasonFit: ['FW', 'transitional'],
    vegan: false,
  },
  {
    id: 'wool-recycled',
    name: 'Recycled wool (mechanical)',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '≥20% recycled wool (often blend)',
    weightRange: { min: 240, max: 600, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['outerwear-coat', 'outerwear-jacket', 'sweater', 'blazer'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'tailored', 'streetwear'],
    seasonFit: ['FW'],
    certifications: ['GRS', 'RCS'],
    vegan: false,
    notes: 'Cardato Recycled is the Prato (Italy) regional certification. Recycled wool is ineligible for RWS — certify via GRS/RCS.',
  },
  {
    id: 'wool-tropical',
    name: 'Tropical wool (lightweight worsted plain)',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% worsted wool',
    weightRange: { min: 170, max: 240, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['tailored', 'minimal'],
    seasonFit: ['SS', 'transitional'],
    vegan: false,
  },
  {
    id: 'wool-fresco',
    name: 'Fresco / high-twist worsted',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% high-twist worsted wool',
    weightRange: { min: 240, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy'],
    seasonFit: ['SS', 'transitional'],
    vegan: false,
  },
  {
    id: 'wool-worsted',
    name: 'Worsted wool (Super 100s/120s/150s)',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% worsted wool',
    weightRange: { min: 240, max: 360, unit: 'gsm' },
    defaultFinish: 'raw',
    finishOptions: ['Super-100s', 'Super-110s', 'Super-120s', 'Super-130s', 'Super-150s', 'Super-180s'],
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy', 'minimal'],
    seasonFit: ['all-year'],
    vegan: false,
  },
  {
    id: 'wool-flannel',
    name: 'Wool flannel',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% wool',
    weightRange: { min: 280, max: 400, unit: 'gsm' },
    defaultFinish: 'fulled',
    zones: ['Body'],
    subtypes: ['suit', 'trouser', 'blazer'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy'],
    seasonFit: ['FW'],
    vegan: false,
    notes: 'Worsted-warp / woolen-weft; brushed finish.',
  },
  {
    id: 'wool-tweed',
    name: 'Wool tweed (Harris / Donegal / Shetland)',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% wool',
    weightRange: { min: 280, max: 500, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['blazer', 'outerwear-jacket', 'outerwear-coat', 'skirt', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['preppy', 'tailored', 'workwear'],
    seasonFit: ['FW'],
    vegan: false,
  },
  {
    id: 'wool-gabardine',
    name: 'Wool gabardine',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% wool',
    weightRange: { min: 240, max: 360, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['trouser', 'outerwear-coat', 'outerwear-jacket'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'workwear'],
    seasonFit: ['transitional', 'FW'],
    vegan: false,
    notes: 'Tightly woven steep twill.',
  },
  {
    id: 'wool-melton',
    name: 'Wool melton',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% wool (heavily milled)',
    weightRange: { min: 400, max: 600, unit: 'gsm' },
    defaultFinish: 'milled',
    zones: ['Body'],
    subtypes: ['outerwear-coat', 'outerwear-jacket'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['tailored', 'workwear', 'preppy'],
    seasonFit: ['FW'],
    vegan: false,
  },
  {
    id: 'wool-loden',
    name: 'Loden',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% wool (boiled / fulled)',
    weightRange: { min: 400, max: 700, unit: 'gsm' },
    defaultFinish: 'fulled',
    zones: ['Body'],
    subtypes: ['outerwear-coat', 'outerwear-jacket'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'workwear'],
    seasonFit: ['FW'],
    vegan: false,
  },
  {
    id: 'wool-jersey',
    name: 'Wool jersey',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% wool',
    weightRange: { min: 200, max: 320, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['dress', 'top', 'loungewear', 'skirt', 'tshirt'],
    priceTier: ['contemporary', 'premium', 'luxury'],
    aestheticTags: ['minimal', 'tailored'],
    seasonFit: ['FW', 'transitional'],
    vegan: false,
  },
  {
    id: 'wool-boucle',
    name: 'Wool bouclé',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% wool (or wool-rich blend)',
    weightRange: { min: 320, max: 480, unit: 'gsm' },
    defaultFinish: 'raw',
    zones: ['Body'],
    subtypes: ['blazer', 'outerwear-jacket', 'outerwear-coat', 'skirt'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'romantic', 'preppy'],
    seasonFit: ['FW'],
    vegan: false,
  },
  {
    id: 'wool-doeskin',
    name: 'Wool doeskin',
    layer: 'L2',
    parentId: 'wool',
    family: 'natural-animal',
    composition: '100% wool',
    weightRange: { min: 320, max: 460, unit: 'gsm' },
    defaultFinish: 'milled',
    zones: ['Body'],
    subtypes: ['outerwear-coat', 'blazer', 'trouser'],
    priceTier: ['luxury'],
    aestheticTags: ['tailored', 'minimal'],
    seasonFit: ['FW'],
    vegan: false,
  },
  // L3 Wool suppliers
  {
    id: 'supplier-vbc',
    name: 'Vitale Barberis Canonico (VBC)',
    layer: 'L3',
    parentId: 'wool',
    family: 'natural-animal',
    composition: 'wool fabrics (mill range)',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'preppy'],
    seasonFit: ['FW', 'transitional'],
    vegan: false,
    supplier: {
      origin: 'Italy (Pratrivero, Biella)',
      tier: 'mill',
      verificationUrl: 'https://vitalebarberiscanonico.com/',
      secondaryUrl: 'https://en.wikipedia.org/wiki/Vitale_Barberis_Canonico',
    },
    notes: 'Founded 1663; 8M meters fabric/year, 5,000 new fabrics/year; supplies Brioni, Kiton, Gucci, Zegna, Loro Piana, Canali, and many bespoke workshops worldwide. Sells half under its own name and half under other brands — true B2B mill.',
  },
  {
    id: 'supplier-reda',
    name: 'Reda 1865',
    layer: 'L3',
    parentId: 'wool',
    family: 'natural-animal',
    composition: 'Merino wool fabrics (mill range)',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser', 'sweater'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored', 'minimal', 'sport'],
    seasonFit: ['all-year'],
    certifications: ['RWS', 'B-Corp'],
    vegan: false,
    supplier: {
      origin: 'Italy (Valdilana, Biella)',
      tier: 'mill',
      verificationUrl: 'https://www.reda1865.com/row/heritage',
      secondaryUrl: 'https://www.bcorporation.net/en-us/find-a-b-corp/company/successori-reda-spa/',
    },
    notes: 'Founded 1865; leading Italian Merino wool mill; vertically integrated from NZ farms to finished fabric; first Italian textile B Corporation; three product lines (Reda 1865 classics, Reda Active sport, Reda Flexo).',
  },
  {
    id: 'supplier-drago',
    name: 'Drago Lanificio',
    layer: 'L3',
    parentId: 'wool',
    family: 'natural-animal',
    composition: 'wool fabrics (mill range)',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored'],
    seasonFit: ['FW', 'transitional'],
    vegan: false,
    supplier: {
      origin: 'Italy (Biella)',
      tier: 'mill',
      verificationUrl: 'https://www.dragobiella.it/en/about-us/',
    },
    notes: 'Founded 1973; vertically integrated wool mill; 1.7M meters/year; supplies major international brands in Japan, Korea, USA. Owns Lanificio Fintes (since 2001).',
  },
  {
    id: 'supplier-cerruti',
    name: 'Lanificio Fratelli Cerruti (Piacenza Group)',
    layer: 'L3',
    parentId: 'wool',
    family: 'natural-animal',
    composition: 'wool fabrics (heritage Biella mill)',
    zones: ['Body'],
    subtypes: ['suit', 'blazer', 'trouser', 'outerwear-coat'],
    priceTier: ['premium', 'luxury'],
    aestheticTags: ['tailored'],
    seasonFit: ['FW'],
    vegan: false,
    supplier: {
      origin: 'Italy (Biella)',
      tier: 'mill',
      verificationUrl: 'https://www.lanificiocerruti.com/',
      secondaryUrl: 'https://en.wikipedia.org/wiki/Lanificio_Fratelli_Cerruti',
    },
    notes: 'Founded 1881; iconic Biella mill; acquired Nov 2022 by Piacenza Group 1733; B2B fabric supplier to multiple international brands.',
  },
  {
    id: 'supplier-botto-giuseppe',
    name: 'Botto Giuseppe',
    layer: 'L3',
    parentId: 'wool',
    family: 'natural-animal',
    composition: 'wool + silk yarns and fabrics',
    zones: ['Body'],
    subtypes: ['sweater', 'knitwear-top', 'dress'],
    priceTier: ['luxury'],
    aestheticTags: ['minimal', 'tailored'],
    seasonFit: ['FW', 'transitional'],
    certifications: ['Cradle-to-Cradle'],
    vegan: false,
    supplier: {
      origin: 'Italy (Valle Mosso, Biella + Tarcento, Udine)',
      tier: 'mill',
      verificationUrl: 'https://www.bottogiuseppe.com/en/yarns/',
      secondaryUrl: 'https://c2ccertified.org/articles/botto-giuseppe-makes-sustainability-the-new-luxury',
    },
    notes: 'Founded 1876; first Italian mill to supply Cradle to Cradle Certified natural wool and silk yarns; produces yarns and fabrics for international luxury customers.',
  },
  {
    id: 'supplier-com-i-stra',
    name: 'Com.i.stra (recycled wool)',
    layer: 'L3',
    parentId: 'wool',
    family: 'natural-animal',
    composition: 'mechanically recycled wool',
    zones: ['Body'],
    subtypes: ['outerwear-coat', 'outerwear-jacket', 'sweater'],
    priceTier: ['contemporary', 'premium'],
    aestheticTags: ['sustainable', 'streetwear'],
    seasonFit: ['FW'],
    certifications: ['GRS', 'RCS'],
    vegan: false,
    supplier: {
      origin: 'Italy (Prato)',
      tier: 'mill',
      verificationUrl: 'https://www.comistra.com/',
    },
    notes: 'Mechanical recycled wool producer in the Prato textile district; specializes in regenerated wool from textile waste; B2B supplier.',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// REMAINING ANIMAL FIBERS — added in subsequent commits:
//  12. Cashmere               (1517-1673)
//  13. Mohair                 (1674-1791)
//  14. Alpaca                 (1792-1920)
//  15. Angora                 (1921-2017)
//  16. Vicuña                 (2018-2094)
//  17. Llama                  (2095-2161)
//  18. Camel hair             (2162-2251)
//  19. Yak                    (2252-2317)
//  20. Qiviut                 (2318-2396)
//  21. Silk                   (2397-2692)
// ═══════════════════════════════════════════════════════════════════════

// ─── Aggregate ─────────────────────────────────────────────────────────────

export const rama1: Material[] = [
  ...cotton,
  ...linen,
  ...hemp,
  ...ramie,
  ...jute,
  ...bamboo,
  ...abaca,
  ...pina,
  ...kapok,
  ...nettle,
  ...wool,
  // ...cashmere, ...mohair, ...alpaca, ...angora, ...vicuna,
  // ...llama, ...camelHair, ...yak, ...qiviut, ...silk,
];
