/**
 * SKU verdict resolver — multi-action verdict per SKU.
 *
 * Felipe's rule: each SKU surfaces ALL the actions the engine detected
 * (typically 1-3). A hero with rising returns shows up as both
 * `carryover` and `investigate`. The buyer reads the stack and decides
 * which one to act on.
 *
 * For each action that involves buying (replenish, carryover) we compute
 * a recommended_units anchored on a healthy rotation target:
 *
 *   recommended_units = (velocity_per_day × target_rotation_days × stores_with_stock)
 *                       − (stock_total + pipeline_total)
 *
 * Default rotation is 4 days (Felipe's baseline) but lives per-action so
 * the UI can let the buyer override per SKU.
 *
 * Output is a `SkuVerdict` that becomes the data shape for the PDF
 * overlay + drawer UI: one row per SKU with multiple action chips.
 */

import type { RecommendationCandidate } from './recommend';
import { generateRationale, shouldCarryUnits, type RationaleContext } from './sku-verdict-rationale';

/** The nine action types a per-SKU verdict can surface. */
export type SkuVerdictAction =
  | 'kill'
  | 'markdown_accelerate'
  | 'replenish'
  | 'resize_down'
  | 'investigate'
  | 'amplify_winner'
  | 'extend_colors'
  | 'carryover'
  | 'hold';

/**
 * Stable display order when a SKU stacks multiple actions. Most
 * consequential / urgent at the top so the buyer scans the right thing
 * first. Kill leads; hold is the fallback when nothing else fits.
 */
const ACTION_DISPLAY_ORDER: SkuVerdictAction[] = [
  'kill',
  'markdown_accelerate',
  'replenish',
  'resize_down',
  'investigate',
  'amplify_winner',
  'extend_colors',
  'carryover',
  'hold',
];

export interface SkuVerdictInput {
  product_fact_id: string;
  /** All candidates emitted by recommend.ts for this SKU. */
  candidates: RecommendationCandidate[];
  /** Operational metrics needed for the rotation-based quantity math. */
  velocity_7d: number | null;
  velocity_d1: number | null;
  stores_active: number | null;
  stores_with_stock: number | null;
  stock_total: number | null;
  pipeline_total: number | null;
}

/** One row in the per-SKU action stack. */
export interface SkuVerdictItem {
  action: SkuVerdictAction;
  /** Confidence of the underlying candidate that produced this action. */
  confidence: number;
  /** Human-readable Spanish sentence explaining the situation +
   *  recommendation. Generated by sku-verdict-rationale templates. */
  rationale: string;
  /** Units to buy (only set for `replenish`). Carryover etc. = null
   *  because "mantener" means "no buy". */
  recommended_units: number | null;
  /** Confidence dimensions inherited from the source candidate. */
  confidence_breakdown: {
    data_completeness: number | null;
    identity: number | null;
    demand: number | null;
    margin: number | null;
    creative_fit: number | null;
  };
  /** Evidence + counter-evidence + assumptions for the drawer detail view. */
  evidence: Record<string, unknown>;
  counter_evidence: Record<string, unknown>;
  assumptions: string[];
  /** Optional warning the engine attached to this candidate. */
  data_sufficiency_warning: string | null;
}

export interface SkuVerdict {
  product_fact_id: string;
  /** 1-N actions, ordered by ACTION_DISPLAY_ORDER. Always at least one
   *  (defaults to `hold` when no candidate maps cleanly). */
  actions: SkuVerdictItem[];
  /** Buyer-editable rotation target in days. Default 4d (Felipe's baseline).
   *  Applied to every replenish/carryover action in the stack. */
  target_rotation_days: number;
  /** Days of stock currently on hand at the SKU's velocity. Same number
   *  across all actions for this SKU so we store it at SKU scope. */
  current_stock_days: number | null;
}

/** Default rotation a healthy fast-fashion product should sit at. Comes
 *  from Felipe's explicit guidance ("una rotación de cuatro días sería
 *  sana"). Buyers can override per SKU in the drawer. */
export const DEFAULT_TARGET_ROTATION_DAYS = 4;

/** Map a recommend.ts action_type to our 7-verb verdict vocabulary.
 *  Returns null for engine actions that don't fit at SKU scope
 *  (new_sku_proposal, family_extension, tension_flag, recolor at lineage
 *  scope, substitute, geographic_redistribute). */
function mapActionType(action: string): SkuVerdictAction | null {
  switch (action) {
    case 'kill':
      return 'kill';
    case 'markdown_accelerate':
    case 'markdown_delay':
      return 'markdown_accelerate';
    case 'replenish':
      return 'replenish';
    case 'resize_up':
      return 'carryover';
    case 'resize_down':
      return 'resize_down';
    case 'investigate':
      return 'investigate';
    case 'carryover':
      return 'carryover';
    default:
      return null;
  }
}

/**
 * Compute target buy units to hit the requested rotation.
 *
 * Math:
 *   velocity_per_day = velocity_d1 (preferred) || velocity_7d / 7
 *   target_units     = velocity_per_day × target_rotation_days
 *   gap              = max(0, target_units − (stock_total + pipeline_total))
 *
 * IMPORTANT: velocity_7d from Zara RNK is the AGGREGATE units across all
 * stores over the 7-day window — it is NOT a per-store rate. Do NOT
 * multiply by stores_with_stock; that produces absurd 7-million-unit
 * recommendations on top SKUs.
 *
 * Returns null for units when no velocity data is available.
 */
export function computeReplenishUnits(
  input: Pick<
    SkuVerdictInput,
    'velocity_7d' | 'velocity_d1' | 'stores_with_stock' | 'stock_total' | 'pipeline_total'
  >,
  targetRotationDays: number
): { recommended_units: number | null; current_stock_days: number | null } {
  const velocityPerDay =
    input.velocity_d1 != null && input.velocity_d1 > 0
      ? input.velocity_d1
      : input.velocity_7d != null && input.velocity_7d > 0
      ? input.velocity_7d / 7
      : null;
  if (velocityPerDay == null) {
    return { recommended_units: null, current_stock_days: null };
  }
  const currentStock = (input.stock_total ?? 0) + (input.pipeline_total ?? 0);
  const targetUnits = velocityPerDay * targetRotationDays;
  const gap = Math.max(0, Math.round(targetUnits - currentStock));
  const currentStockDays = velocityPerDay > 0 ? currentStock / velocityPerDay : null;
  return {
    recommended_units: gap,
    current_stock_days: currentStockDays != null ? Math.round(currentStockDays * 10) / 10 : null,
  };
}

/**
 * Build a single SkuVerdictItem from a recommend.ts candidate.
 * Returns null when the candidate's action doesn't map to a SKU-scope
 * verdict (those are filtered out upstream).
 */
function buildVerdictItem(
  candidate: RecommendationCandidate,
  input: SkuVerdictInput,
  targetRotationDays: number,
  identity: { product_name: string | null; family_code: string | null; model_ref: string | null }
): SkuVerdictItem | null {
  const action = mapActionType(candidate.action_type);
  if (!action) return null;

  // Only `replenish` carries a recommended_units. Carryover = "no buy",
  // markdown = "lower price not raise stock", investigate = "diagnose
  // before acting", etc. Surfacing a number on those confuses the buyer.
  const carry = shouldCarryUnits(action);
  const { recommended_units, current_stock_days } = carry
    ? computeReplenishUnits(input, targetRotationDays)
    : { recommended_units: null, current_stock_days: null };

  const evidence = (candidate.evidence as Record<string, unknown>) ?? {};
  const rationaleCtx: RationaleContext = {
    product_name: identity.product_name,
    family_code: identity.family_code,
    model_ref: identity.model_ref,
    velocity_7d: input.velocity_7d,
    velocity_ratio: typeof evidence.velocity_ratio === 'number' ? (evidence.velocity_ratio as number) : null,
    returns_pct: typeof evidence.returns_pct === 'number' ? (evidence.returns_pct as number) : null,
    effective_margin: typeof evidence.effective_margin === 'number' ? (evidence.effective_margin as number) : null,
    lifecycle_stage: typeof evidence.lifecycle_stage === 'string' ? (evidence.lifecycle_stage as string) : null,
    sell_through_bought_pct:
      typeof evidence.sell_through_bought_pct === 'number'
        ? (evidence.sell_through_bought_pct as number)
        : null,
    stores_active: input.stores_active,
    current_stock_days,
    recommended_units,
    target_rotation_days: targetRotationDays,
  };

  return {
    action,
    confidence: Number(candidate.confidence_action) || 0,
    rationale: generateRationale(action, rationaleCtx),
    recommended_units,
    confidence_breakdown: {
      data_completeness: candidate.confidence_data_completeness ?? null,
      identity: candidate.confidence_identity ?? null,
      demand: candidate.confidence_demand ?? null,
      margin: candidate.confidence_margin ?? null,
      creative_fit: candidate.confidence_creative_fit ?? null,
    },
    evidence,
    counter_evidence: (candidate.counter_evidence as Record<string, unknown>) ?? {},
    assumptions: (candidate.assumptions as string[]) ?? [],
    data_sufficiency_warning: candidate.data_sufficiency_warning,
  };
}

/**
 * Resolve a SKU's full set of candidates into a stack of verdict items.
 * Multiple actions for the same SKU are allowed and surfaced — Felipe's
 * rule: "se ponen todas las que haya, puede tener dos o tres acciones".
 *
 * When two candidates collapse to the same SkuVerdictAction (e.g. two
 * markdown variants) we keep the one with higher confidence. When no
 * candidate maps to a usable action, we emit a single `hold`.
 */
export function resolveSkuVerdict(
  input: SkuVerdictInput,
  targetRotationDays: number = DEFAULT_TARGET_ROTATION_DAYS,
  identity: { product_name: string | null; family_code: string | null; model_ref: string | null } = {
    product_name: null,
    family_code: null,
    model_ref: null,
  }
): SkuVerdict {
  // Build items for every candidate that maps to a SKU-scope action.
  const itemsByAction = new Map<SkuVerdictAction, SkuVerdictItem>();
  for (const c of input.candidates) {
    const item = buildVerdictItem(c, input, targetRotationDays, identity);
    if (!item) continue;
    const existing = itemsByAction.get(item.action);
    if (!existing || item.confidence > existing.confidence) {
      itemsByAction.set(item.action, item);
    }
  }

  // Sort by stable display order so the UI always shows the most
  // consequential action first.
  const actions: SkuVerdictItem[] = [];
  for (const a of ACTION_DISPLAY_ORDER) {
    const item = itemsByAction.get(a);
    if (item) actions.push(item);
  }

  // Diagnostic: current stock days at the SKU's velocity. Same number
  // for the whole SKU (independent of which actions apply).
  const { current_stock_days } = computeReplenishUnits(input, targetRotationDays);

  if (actions.length === 0) {
    // No usable signal — emit a hold so the UI always has something to
    // render and the buyer sees "nothing actionable here, reassess".
    const fallback = input.candidates[0];
    const evidence = (fallback?.evidence as Record<string, unknown>) ?? {};
    const fallbackCtx: RationaleContext = {
      product_name: identity.product_name,
      family_code: identity.family_code,
      model_ref: identity.model_ref,
      velocity_7d: input.velocity_7d,
      velocity_ratio: typeof evidence.velocity_ratio === 'number' ? (evidence.velocity_ratio as number) : null,
      returns_pct: typeof evidence.returns_pct === 'number' ? (evidence.returns_pct as number) : null,
      effective_margin: typeof evidence.effective_margin === 'number' ? (evidence.effective_margin as number) : null,
      lifecycle_stage: typeof evidence.lifecycle_stage === 'string' ? (evidence.lifecycle_stage as string) : null,
      sell_through_bought_pct:
        typeof evidence.sell_through_bought_pct === 'number'
          ? (evidence.sell_through_bought_pct as number)
          : null,
      stores_active: input.stores_active,
      current_stock_days,
      recommended_units: null,
      target_rotation_days: targetRotationDays,
    };
    actions.push({
      action: 'hold',
      confidence: 0.3,
      rationale: generateRationale('hold', fallbackCtx),
      recommended_units: null,
      confidence_breakdown: {
        data_completeness: fallback?.confidence_data_completeness ?? null,
        identity: fallback?.confidence_identity ?? null,
        demand: fallback?.confidence_demand ?? null,
        margin: fallback?.confidence_margin ?? null,
        creative_fit: fallback?.confidence_creative_fit ?? null,
      },
      evidence,
      counter_evidence: (fallback?.counter_evidence as Record<string, unknown>) ?? {},
      assumptions: (fallback?.assumptions as string[]) ?? [],
      data_sufficiency_warning:
        fallback?.data_sufficiency_warning ??
        'No clear signal for this SKU — hold and reassess next run',
    });
  }

  return {
    product_fact_id: input.product_fact_id,
    actions,
    target_rotation_days: targetRotationDays,
    current_stock_days,
  };
}

/**
 * Append an `amplify_winner` action when the SKU is materially out-
 * performing its family (Felipe's "vende 2× la media" rule). For these
 * winners, surfacing "carryover" alone is insufficient — the right
 * second-order action is "design the next generation in this winning
 * archetype" so next season captures the demand the current SKU is
 * already proving.
 *
 * Trigger: demand_score ≥ 0.7 (top quintile in family) + hero indicators
 * (sell-through ≥ 50%, returns ≤ 18%). The signal becomes a strong
 * candidate-for-followups for the merchandising team to brief design.
 */
export function appendAmplifyWinnerAction(
  verdict: SkuVerdict,
  signals: {
    demand_score: number | null;
    sell_through_bought_pct: number | null;
    returns_pct: number | null;
    velocity_7d: number | null;
    family_code: string | null;
    /** 1-based PDF rank — the order the buyer sees in the RNK report. This
     *  is the SOURCE ranking from Zara, generally by revenue. */
    pdf_rank: number | null;
    /** 1-based rank by velocity_7d across the run (1 = highest units). */
    velocity_rank: number | null;
    /** velocity_7d divided by family average velocity. */
    family_velocity_ratio: number | null;
    /** Color names from the creative brief's color_story. When present, the
     *  rationale recommends shooting the winner silhouette in these colors. */
    brief_colors: string[];
    /** Color name of THIS SKU. Excluded from the brief-color suggestions
     *  since proposing the same colour the SKU already sells in is moot. */
    current_color: string | null;
  }
): SkuVerdict {
  // Block ONLY when returns are catastrophic — Zara winners can hover at
  // 25-30% returns and still be heroes. Below 0.35 we still propose
  // amplification (the buyer can downgrade via override). The rationale
  // surfaces the returns_pct so they see the risk.
  if ((signals.returns_pct ?? 0) > 0.35) return verdict;

  // Four independent triggers for hero detection. Any one fires.
  const pdfTopN =
    signals.pdf_rank != null && signals.pdf_rank <= 10;
  const scoreBased =
    (signals.demand_score ?? 0) >= 0.7 &&
    (signals.sell_through_bought_pct ?? 0) >= 0.5;
  const rankBased =
    signals.velocity_rank != null && signals.velocity_rank <= 10;
  const familyBased =
    (signals.family_velocity_ratio ?? 0) >= 2.0;

  if (!pdfTopN && !scoreBased && !rankBased && !familyBased) return verdict;
  // Skip if already present.
  if (verdict.actions.some((a) => a.action === 'amplify_winner')) return verdict;

  // Rationale composition: lead with the strongest visible signal.
  const parts: string[] = [];
  if (signals.pdf_rank != null && signals.pdf_rank <= 10) {
    parts.push(`top ${signals.pdf_rank} del RNK Zara`);
  } else if (signals.velocity_rank != null && signals.velocity_rank <= 10) {
    parts.push(`top ${signals.velocity_rank} en velocidad del run`);
  }
  if ((signals.family_velocity_ratio ?? 0) >= 2.0) {
    parts.push(
      `vende ${signals.family_velocity_ratio!.toFixed(1)}× la media de su familia${
        signals.family_code ? ` ${signals.family_code}` : ''
      }`
    );
  }
  if ((signals.demand_score ?? 0) >= 0.7) {
    parts.push(
      `demand-score ${Math.round((signals.demand_score ?? 0) * 100)}% (top quintil)`
    );
  }
  if ((signals.sell_through_bought_pct ?? 0) >= 0.5) {
    parts.push(
      `sell-through ${Math.round((signals.sell_through_bought_pct ?? 0) * 100)}%`
    );
  }
  const head = parts.length > 0
    ? `Hero confirmado: ${parts.join(' · ')}.`
    : 'Hero confirmado.';

  // Surface concrete colours from the brief's color_story so the
  // recommendation is actionable (Felipe: "proponer EL color, no solo
  // identificar el ganador"). Skip the SKU's own colour.
  const currentColorLc = (signals.current_color ?? '').trim().toLowerCase();
  const candidateColors = (signals.brief_colors ?? [])
    .map((c) => (c ?? '').trim())
    .filter(Boolean)
    .filter((c) => c.toLowerCase() !== currentColorLc);
  const briefColorSentence =
    candidateColors.length > 0
      ? ` Probar también la misma silueta en colores del moodboard: ${candidateColors
          .slice(0, 4)
          .join(', ')}.`
      : '';

  const rationale = `${head} Más allá de mantenerlo, diseñar 2-3 secuelas siguiendo este patrón (silueta + material + paleta) captura esa demanda en próxima temporada.${briefColorSentence}`;

  // Confidence: highest of the four signals (capped at 0.95).
  const confScore = (signals.demand_score ?? 0) >= 0.7 ? 0.85 : 0;
  const confVelRank =
    signals.velocity_rank != null && signals.velocity_rank <= 10
      ? 0.92 - signals.velocity_rank * 0.02
      : 0;
  const confPdfRank =
    signals.pdf_rank != null && signals.pdf_rank <= 10
      ? 0.95 - signals.pdf_rank * 0.02
      : 0;
  const confFamily =
    (signals.family_velocity_ratio ?? 0) >= 2.0
      ? Math.min(0.95, 0.7 + (signals.family_velocity_ratio! - 2) * 0.1)
      : 0;
  const confidence = Math.min(
    0.95,
    Math.max(confScore, confVelRank, confPdfRank, confFamily, 0.7)
  );

  const newItem: SkuVerdictItem = {
    action: 'amplify_winner',
    confidence,
    rationale,
    recommended_units: null,
    confidence_breakdown: {
      data_completeness: null,
      identity: null,
      demand: signals.demand_score ?? null,
      margin: null,
      creative_fit: null,
    },
    evidence: {
      demand_score: signals.demand_score,
      sell_through_bought_pct: signals.sell_through_bought_pct,
      returns_pct: signals.returns_pct,
      velocity_7d: signals.velocity_7d,
      family_code: signals.family_code,
      pdf_rank: signals.pdf_rank,
      velocity_rank: signals.velocity_rank,
      family_velocity_ratio: signals.family_velocity_ratio,
      proposed_brief_colors: candidateColors.slice(0, 4),
    },
    counter_evidence: {},
    assumptions: [
      'Recomendación estratégica al equipo de diseño/merch, no operacional.',
    ],
    data_sufficiency_warning: null,
  };

  // Reinsert with stable display order.
  const map = new Map<SkuVerdictAction, SkuVerdictItem>();
  for (const a of verdict.actions) map.set(a.action, a);
  map.set('amplify_winner', newItem);
  const reordered: SkuVerdictItem[] = [];
  for (const a of ACTION_DISPLAY_ORDER) {
    const item = map.get(a);
    if (item) reordered.push(item);
  }
  return { ...verdict, actions: reordered };
}

/**
 * Append a synthetic `extend_colors` action to a SKU verdict when its
 * lineage has a `recolor` candidate (color winner detected). The
 * recommendation is at the lineage level so all sibling SKUs share it.
 *
 * The action carries the winning color name + confidence; the rationale
 * surfaces both pieces in human language. Returns a new SkuVerdict.
 */
export interface LineageColorWinner {
  color_name: string;
  color_code: string;
  confidence: number;
  rank: string;
  demand_score: number | null;
}

export function appendExtendColorsAction(
  verdict: SkuVerdict,
  winner: LineageColorWinner,
  identity: { product_name: string | null; family_code: string | null; model_ref: string | null }
): SkuVerdict {
  // If extend_colors already in the stack, keep the higher-confidence one.
  const existing = verdict.actions.find((a) => a.action === 'extend_colors');
  if (existing && existing.confidence >= winner.confidence) return verdict;

  const rationale =
    winner.rank === 'top'
      ? `El color ${winner.color_name} es el ganador dentro de este lineage (${Math.round(winner.confidence * 100)}% confianza). Considera extender la paleta con tonos adyacentes para amplificar el winner.`
      : `Color ${winner.color_name} detectado como variante a evaluar dentro del lineage. Validar si extender o reasignar share de compra.`;

  const newItem: SkuVerdictItem = {
    action: 'extend_colors',
    confidence: winner.confidence,
    rationale,
    recommended_units: null,
    confidence_breakdown: {
      data_completeness: null,
      identity: null,
      demand: winner.demand_score ?? null,
      margin: null,
      creative_fit: null,
    },
    evidence: {
      anchor_color_name: winner.color_name,
      anchor_color_code: winner.color_code,
      rank: winner.rank,
      lineage_family: identity.family_code ?? null,
    },
    counter_evidence: {},
    assumptions: [
      'Recomendación al nivel de lineage: aplica a todos los SKUs del mismo modelo.',
    ],
    data_sufficiency_warning: null,
  };

  // Reinsert with stable display order.
  const map = new Map<SkuVerdictAction, SkuVerdictItem>();
  for (const a of verdict.actions) map.set(a.action, a);
  map.set('extend_colors', newItem);
  const reordered: SkuVerdictItem[] = [];
  for (const a of ACTION_DISPLAY_ORDER) {
    const item = map.get(a);
    if (item) reordered.push(item);
  }
  return { ...verdict, actions: reordered };
}

/**
 * Batch-resolve all SKUs in a run into a verdict-per-SKU map.
 *
 * `inputsByProductFactId` keys the per-SKU operational metrics (velocity,
 * stock, etc.) by product_fact_id. `candidatesByProductFactId` maps the
 * raw candidates emitted by recommend.ts. SKUs that appear in inputs but
 * have no candidates still get a `hold` verdict.
 */
export function resolveAllSkuVerdicts(
  inputsByProductFactId: Map<string, Omit<SkuVerdictInput, 'candidates'>>,
  candidatesByProductFactId: Map<string, RecommendationCandidate[]>,
  identityByProductFactId: Map<string, { product_name: string | null; family_code: string | null; model_ref: string | null }>,
  defaultTargetRotationDays: number = DEFAULT_TARGET_ROTATION_DAYS,
  perSkuOverrides?: Map<string, number>
): SkuVerdict[] {
  const out: SkuVerdict[] = [];
  for (const [pid, base] of Array.from(inputsByProductFactId.entries())) {
    const candidates = candidatesByProductFactId.get(pid) ?? [];
    const rotation = perSkuOverrides?.get(pid) ?? defaultTargetRotationDays;
    const identity = identityByProductFactId.get(pid) ?? {
      product_name: null,
      family_code: null,
      model_ref: null,
    };
    out.push(
      resolveSkuVerdict(
        { ...base, product_fact_id: pid, candidates },
        rotation,
        identity
      )
    );
  }
  return out;
}
