/**
 * Headline KPIs — the 5 buyer-facing top-row numbers per spec v1.
 *
 * Source of truth: memory/product-spec_aimily-in-season-2026-05-17.md §3.1.
 *
 * The 5 KPIs that a senior buyer trained in classroom (LCF, FIT, LIM) expects
 * to see BEFORE looking at any verdict:
 *   1. GMROI                   (Kincade & Gibson Ch.7 — target fashion 3.0–3.5)
 *   2. STR vs plan curve       (delta in pp from plan at this week-of-season)
 *   3. FWOC / lead time ratio  (< 1 = stockout risk · > 2 = oversupplied)
 *   4. Stock-to-sales ratio    (spike = parked stock)
 *   5. Maintained markup %     (gap vs initial markup reveals markdown erosion)
 *
 * Each KPI carries a `source: 'tenant' | 'synthetic'` tag so the UI can
 * label estimates explicitly (graceful degradation pattern — see
 * feedback_aimily-graceful-degradation-tenant-input-or-synthetic.md).
 */

export interface HeadlineKpiValue {
  /** The numeric value, or null when neither tenant input nor synthetic
   *  derivation can produce it (extremely rare — would mean missing both
   *  pvp AND velocity). */
  value: number | null;
  /** Where the value came from. 'tenant' = computed from explicit tenant
   *  inputs only. 'synthetic' = at least one input was a retailer-profile
   *  default rather than tenant-provided. */
  source: 'tenant' | 'synthetic';
  /** Free-text qualifier for the UI — e.g., "above target" / "below target"
   *  / "estimate" — kept short so it fits inside a small badge. */
  label?: string;
}

export interface HeadlineKpis {
  /** Gross Margin Return On Inventory (Kincade & Gibson Ch.7). Target
   *  fashion 3.0–3.5; below 2.5 = problem. */
  gmroi: HeadlineKpiValue;
  /** Sell-through vs plan curve, in percentage points (positive =
   *  ahead of plan, negative = behind). */
  str_vs_plan_pp: HeadlineKpiValue;
  /** Forward Weeks of Cover ÷ supplier lead time. <1 = stockout risk,
   *  >2 = oversupplied. */
  fwoc_lt_ratio: HeadlineKpiValue;
  /** Stock-to-sales ratio = stock value / weekly sales value. */
  s_s_ratio: HeadlineKpiValue;
  /** Maintained markup % = effective gross margin / sales after markdowns. */
  maintained_markup_pct: HeadlineKpiValue;
}

export interface HeadlineKpiInputs {
  pvp: number | null;
  cost_estimate: number | null;
  margin_pct_list: number | null;
  velocity_7d: number | null;
  total_sold: number | null;
  total_bought: number | null;
  sell_through_bought_pct: number | null;
  returns_pct: number | null;
  pipeline_total: number | null;
  stock_total: number | null;
  days_in_store: number | null;
  /** Tenant-supplied lead time (days). Synthetic fallback per retailer
   *  profile when absent. */
  supplier_lead_time_days: number | null;
  /** Tenant-supplied plan curve. Each entry maps week-of-season to a
   *  target sell-through %. Synthetic fallback (linear ramp) when absent. */
  planned_str_curve: Array<{ week_of_season: number; target_str_pct: number }> | null;
  /** Tenant retailer profile (Zara fast-fashion / Mango mid-market / Shopify SMB).
   *  Drives synthetic defaults. */
  retailer_profile: 'zara_fast_fashion' | 'mango_mid_market' | 'shopify_smb' | 'generic';
}

interface ProfileDefaults {
  /** Default lead time when tenant doesn't provide it. */
  supplier_lead_time_days: number;
  /** Season length in weeks. Used to derive plan curve when tenant doesn't provide it. */
  season_weeks: number;
  /** Target final sell-through at end-of-season — drives synthetic plan curve slope. */
  target_final_str_pct: number;
}

const PROFILE_DEFAULTS: Record<HeadlineKpiInputs['retailer_profile'], ProfileDefaults> = {
  zara_fast_fashion: {
    supplier_lead_time_days: 15,    // Ferdows et al. 2004 HBR
    season_weeks: 6,                // Caro et al. 2010 — store-level SKU life cycle
    target_final_str_pct: 0.85,     // Zara folklore (industry-cited, not Inditex-disclosed)
  },
  mango_mid_market: {
    supplier_lead_time_days: 60,
    season_weeks: 13,               // generic quarter
    target_final_str_pct: 0.70,
  },
  shopify_smb: {
    supplier_lead_time_days: 75,
    season_weeks: 13,
    target_final_str_pct: 0.65,
  },
  generic: {
    supplier_lead_time_days: 60,
    season_weeks: 13,
    target_final_str_pct: 0.70,
  },
};

/**
 * Compute the 5 headline KPIs from per-SKU operational inputs.
 *
 * Graceful degradation: each KPI tagged with 'tenant' (computed from
 * explicit tenant inputs only) or 'synthetic' (≥1 input was a retailer-
 * profile default). The UI surfaces 'synthetic' as an "estimate" badge.
 */
export function computeHeadlineKpis(input: HeadlineKpiInputs): HeadlineKpis {
  const defaults = PROFILE_DEFAULTS[input.retailer_profile];

  // ── 1. GMROI ─────────────────────────────────────────────────────────────
  // Numerator: gross margin $ generated by this SKU =
  //   total_sold × (pvp − cost_estimate) × (1 − returns_pct)
  // Denominator: avg inventory at cost ≈ pipeline_total × cost_estimate
  // (proxy — true average needs time-series; we use point-in-time pipeline).
  let gmroi: HeadlineKpiValue = { value: null, source: 'tenant' };
  if (
    input.pvp != null &&
    input.cost_estimate != null &&
    input.cost_estimate > 0 &&
    input.pipeline_total != null &&
    input.pipeline_total > 0 &&
    input.total_sold != null
  ) {
    const grossMarginPerUnit = input.pvp - input.cost_estimate;
    const grossMarginDollars =
      input.total_sold * grossMarginPerUnit * (1 - (input.returns_pct ?? 0));
    const avgInventoryAtCost = input.pipeline_total * input.cost_estimate;
    const gmroiValue = avgInventoryAtCost > 0 ? grossMarginDollars / avgInventoryAtCost : null;
    if (gmroiValue != null) {
      let label = '';
      if (gmroiValue >= 3.0) label = 'on target';
      else if (gmroiValue >= 2.5) label = 'below target';
      else label = 'critical';
      gmroi = { value: Math.round(gmroiValue * 100) / 100, source: 'tenant', label };
    }
  }

  // ── 2. STR vs plan curve ─────────────────────────────────────────────────
  // Compute the current week-of-season from days_in_store, look up the
  // planned STR target, return (actual − planned) in percentage points.
  let strVsPlan: HeadlineKpiValue = { value: null, source: 'tenant' };
  if (input.sell_through_bought_pct != null && input.days_in_store != null) {
    const weekOfSeason = Math.max(1, Math.floor(input.days_in_store / 7) + 1);
    let plannedStr: number | null = null;
    let source: 'tenant' | 'synthetic' = 'tenant';
    if (input.planned_str_curve && input.planned_str_curve.length > 0) {
      // Find the closest planned point for this week (linear interpolation
      // between the two nearest entries when exact match isn't available).
      const sorted = [...input.planned_str_curve].sort(
        (a, b) => a.week_of_season - b.week_of_season
      );
      let prev: { week_of_season: number; target_str_pct: number } | null = null;
      let next: { week_of_season: number; target_str_pct: number } | null = null;
      for (const p of sorted) {
        if (p.week_of_season <= weekOfSeason) prev = p;
        if (p.week_of_season >= weekOfSeason && next == null) next = p;
      }
      if (prev && next && prev.week_of_season !== next.week_of_season) {
        const t = (weekOfSeason - prev.week_of_season) / (next.week_of_season - prev.week_of_season);
        plannedStr = prev.target_str_pct + t * (next.target_str_pct - prev.target_str_pct);
      } else if (prev) {
        plannedStr = prev.target_str_pct;
      } else if (next) {
        plannedStr = next.target_str_pct;
      }
    }
    if (plannedStr == null) {
      // Synthetic linear ramp from 0 at week 1 to target_final_str_pct at
      // season_weeks. This is the canonical fast-fashion assumption when
      // the tenant doesn't supply their plan curve.
      const t = Math.min(1, weekOfSeason / defaults.season_weeks);
      plannedStr = t * defaults.target_final_str_pct;
      source = 'synthetic';
    }
    const deltaPp = (input.sell_through_bought_pct - plannedStr) * 100;
    let label = '';
    if (deltaPp >= 5) label = 'ahead of plan';
    else if (deltaPp >= -5) label = 'on plan';
    else label = 'behind plan';
    strVsPlan = { value: Math.round(deltaPp * 10) / 10, source, label };
  }

  // ── 3. FWOC / lead time ratio ────────────────────────────────────────────
  let fwocLt: HeadlineKpiValue = { value: null, source: 'tenant' };
  if (input.pipeline_total != null && input.velocity_7d != null && input.velocity_7d > 0) {
    const fwocWeeks = input.pipeline_total / Math.max(input.velocity_7d, 1);
    const leadTimeDays = input.supplier_lead_time_days ?? defaults.supplier_lead_time_days;
    const leadTimeWeeks = leadTimeDays / 7;
    const ratio = leadTimeWeeks > 0 ? fwocWeeks / leadTimeWeeks : null;
    if (ratio != null) {
      let label = '';
      if (ratio < 1) label = 'stockout risk';
      else if (ratio > 2) label = 'oversupplied';
      else label = 'healthy';
      fwocLt = {
        value: Math.round(ratio * 10) / 10,
        source: input.supplier_lead_time_days != null ? 'tenant' : 'synthetic',
        label,
      };
    }
  }

  // ── 4. Stock-to-sales ratio ──────────────────────────────────────────────
  let ssRatio: HeadlineKpiValue = { value: null, source: 'tenant' };
  if (
    input.pipeline_total != null &&
    input.cost_estimate != null &&
    input.velocity_7d != null &&
    input.velocity_7d > 0 &&
    input.pvp != null
  ) {
    const stockValue = input.pipeline_total * input.cost_estimate;
    const weeklySalesValue = input.velocity_7d * input.pvp;
    const ratio = weeklySalesValue > 0 ? stockValue / weeklySalesValue : null;
    if (ratio != null) {
      let label = '';
      if (ratio < 4) label = 'lean';
      else if (ratio > 10) label = 'parked stock';
      else label = 'normal';
      ssRatio = { value: Math.round(ratio * 10) / 10, source: 'tenant', label };
    }
  }

  // ── 5. Maintained markup % ──────────────────────────────────────────────
  // Approximate as effective margin ÷ pvp (post-returns), expressed as %.
  // True maintained markup requires markdown history we don't have on
  // per-period basis yet — this is the conservative estimate.
  let maintainedMu: HeadlineKpiValue = { value: null, source: 'tenant' };
  if (input.pvp != null && input.cost_estimate != null && input.margin_pct_list != null) {
    const effectiveMargin =
      input.pvp * input.margin_pct_list * (1 - (input.returns_pct ?? 0)) -
      input.cost_estimate * 0.15 * (input.returns_pct ?? 0);
    const mu = effectiveMargin / input.pvp;
    if (Number.isFinite(mu)) {
      let label = '';
      const initial = input.margin_pct_list;
      if (mu >= initial - 0.05) label = 'no erosion';
      else if (mu >= initial - 0.15) label = 'slight erosion';
      else label = 'eroding';
      maintainedMu = { value: Math.round(mu * 1000) / 10, source: 'tenant', label }; // as pct
    }
  }

  return {
    gmroi,
    str_vs_plan_pp: strVsPlan,
    fwoc_lt_ratio: fwocLt,
    s_s_ratio: ssRatio,
    maintained_markup_pct: maintainedMu,
  };
}
