/**
 * Apply the vision-validated Zara color taxonomy to strategy_taxonomies.
 *
 * Context (2026-05-18):
 *   - The original seed in migration 059d (v1.0.0) was a guessed starter
 *     mapping that proved wrong on 41 of 43 codes when Claude Vision
 *     validated against the V26 RNK PDF photos.
 *   - scripts/extract-zara-color-mapping.ts produced
 *     memory/zara-color-taxonomy-proposed.json with 43 validated codes.
 *   - Felipe also clarified (2026-05-18) that Zara does NOT use the
 *     NRF/GS1 standard cleanly — code 800 = negro with 18 unanimous
 *     observations contradicts NRF's 800 = orange. So we don't use NRF
 *     as the fallback either; we trust the observed mapping for Zara.
 *
 * This script:
 *   1. Reads the validated mapping JSON.
 *   2. Deactivates the existing v1.0.0 color taxonomy row.
 *   3. Inserts a new v1.1.0 row with the validated mapping + reviewer
 *      notes explaining the provenance.
 *   4. Marks the new row as is_active=true.
 *
 * The taxonomy is per-tenant. For aimily-internal (the V26 corpus
 * tenant), this is the source of truth going forward. Future tenants
 * will get their own taxonomy via the same vision extractor.
 *
 * Usage:
 *   npx tsx --env-file=.env.local scripts/apply-validated-zara-color-taxonomy.ts
 */

import { supabaseAdmin } from '@/lib/supabase-admin';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

const TENANT_ID = '60105796-ea66-4355-b904-e10296436ff9';
const NEW_VERSION = '1.1.0-vision-validated';
const PROPOSED_JSON_PATH = path.resolve(__dirname, '..', 'memory', 'zara-color-taxonomy-proposed.json');

interface ProposedTaxonomy {
  generated_at: string;
  source_id: string;
  tenant_id: string;
  n_codes: number;
  consensus_stats: { unanimous: number; majority: number; split: number; single: number };
  code_to_name: Record<string, string>;
  code_to_hex: Record<string, string>;
  per_code_details: Array<{
    color_code: string;
    n_observations: number;
    proposed_name_es: string;
    consensus: 'unanimous' | 'majority' | 'split' | 'single';
    sample_model_refs: string[];
  }>;
}

async function main() {
  console.log('\n=== Apply validated Zara color taxonomy ===\n');

  // 1) Load the validated mapping.
  const raw = await readFile(PROPOSED_JSON_PATH, 'utf-8');
  const proposed = JSON.parse(raw) as ProposedTaxonomy;
  console.log(`Loaded ${proposed.n_codes} validated codes`);
  console.log(`Consensus: ${proposed.consensus_stats.unanimous} unanimous, ${proposed.consensus_stats.majority} majority, ${proposed.consensus_stats.split} split, ${proposed.consensus_stats.single} single\n`);

  // 2) Snapshot the current active taxonomy for the audit trail.
  const { data: currentRows } = await supabaseAdmin
    .from('strategy_taxonomies')
    .select('id, version, mapping, is_active, reviewer_notes')
    .eq('tenant_id', TENANT_ID)
    .eq('taxonomy_kind', 'color')
    .order('created_at', { ascending: false });
  console.log(`Existing color taxonomy rows: ${currentRows?.length ?? 0}`);
  if (currentRows) {
    for (const row of currentRows as Array<{ version: string; is_active: boolean }>) {
      console.log(`  v${row.version} · is_active=${row.is_active}`);
    }
  }
  console.log();

  // 3) Deactivate every existing color taxonomy row for this tenant.
  console.log('Deactivating prior color taxonomy versions...');
  const { error: deactErr } = await supabaseAdmin
    .from('strategy_taxonomies')
    .update({ is_active: false })
    .eq('tenant_id', TENANT_ID)
    .eq('taxonomy_kind', 'color');
  if (deactErr) {
    console.error('Deactivate failed:', deactErr.message);
    process.exit(1);
  }
  console.log('Done.\n');

  // 4) Insert the new v1.1.0 row with the validated mapping.
  const reviewerNotes =
    `Vision-validated taxonomy for Zara (tenant aimily-internal). ` +
    `Generated by scripts/extract-zara-color-mapping.ts on ${proposed.generated_at} from ` +
    `${proposed.n_codes} codes observed across the V26 RNK PDF corpus (113 SKU photos). ` +
    `Consensus stats: ${proposed.consensus_stats.unanimous} unanimous, ` +
    `${proposed.consensus_stats.majority} majority, ${proposed.consensus_stats.split} split, ` +
    `${proposed.consensus_stats.single} single observation. ` +
    `Supersedes the v1.0.0 starter seed in migration 059d which had 41 of 43 codes mismapped ` +
    `(verified divergence: 250 seed=negro / observed=crudo; 401 seed=blanco / observed=azul noche; etc.). ` +
    `Zara does NOT follow the NRF/GS1 standard cleanly — observed code 800=negro with 18 unanimous ` +
    `observations contradicts NRF 800=orange, so we trust observation over external standard. ` +
    `For codes with only 1 observation ('single' consensus), confidence is lower — these may need ` +
    `revisiting if a future run shows divergence.`;

  // Compose the mapping in the same shape the existing engine expects.
  const mapping = {
    code_to_name: proposed.code_to_name,
    code_to_hex: proposed.code_to_hex,
    // Embed per-code provenance so the UI can later show "validated by 15
    // unanimous observations" alongside any verdict that uses this code.
    code_provenance: Object.fromEntries(
      proposed.per_code_details.map((d) => [
        d.color_code,
        {
          n_observations: d.n_observations,
          consensus: d.consensus,
          sample_model_refs: d.sample_model_refs.slice(0, 3),
        },
      ])
    ),
  };

  console.log(`Inserting v${NEW_VERSION} with ${Object.keys(mapping.code_to_name).length} codes...`);
  const { data: inserted, error: insErr } = await supabaseAdmin
    .from('strategy_taxonomies')
    .insert({
      tenant_id: TENANT_ID,
      taxonomy_kind: 'color',
      version: NEW_VERSION,
      mapping,
      is_active: true,
      reviewer_notes: reviewerNotes,
    })
    .select('id, version, is_active')
    .single();
  if (insErr) {
    console.error('Insert failed:', insErr.message);
    process.exit(1);
  }
  console.log(`Inserted: ${(inserted as { id: string; version: string; is_active: boolean }).id} · v${(inserted as { version: string }).version} · is_active=true\n`);

  // 5) Verify state after the change.
  const { data: after } = await supabaseAdmin
    .from('strategy_taxonomies')
    .select('version, is_active')
    .eq('tenant_id', TENANT_ID)
    .eq('taxonomy_kind', 'color')
    .order('created_at', { ascending: false });
  console.log(`Color taxonomy state for tenant ${TENANT_ID}:`);
  for (const row of (after ?? []) as Array<{ version: string; is_active: boolean }>) {
    console.log(`  v${row.version} · is_active=${row.is_active}`);
  }

  // 6) Quick spot-check: confirm code 401 is now azul noche, code 250 is crudo, code 800 is negro.
  console.log('\nSpot check (the codes Felipe specifically verified):');
  console.log(`  401 → ${proposed.code_to_name['401']} (was 'blanco' in seed; Felipe verified is 'azul noche')`);
  console.log(`  250 → ${proposed.code_to_name['250']} (was 'negro' in seed; 15 obs majority)`);
  console.log(`  800 → ${proposed.code_to_name['800']} (was 'negro_carbon' in seed; 18 obs majority — Felipe confirmed)`);

  console.log('\n=== Done ===\n');
  console.log('Next step: re-execute the orchestrator for the V26 run so the verdict rationales ');
  console.log('pick up the new color names. The candidates and sku_scores reference colors via ');
  console.log('the taxonomy at scoring time, so a re-run via scripts/reexecute-strategy-run.ts ');
  console.log('will refresh the prose.\n');
}

main().catch((e) => {
  console.error('Fatal:', e);
  process.exit(1);
});
