-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 057 · Aimily Studio · Multi-format derivatives
--
-- Each Studio output (collection_asset with studio_project_id) is generated
-- once at master resolution (2048x2048 or 1024x1536 depending on AI model),
-- and then sharp post-processing derives 12 channel-specific formats:
-- Instagram square / portrait / story, TikTok, Pinterest, Facebook Ad,
-- LinkedIn, Twitter, Web hero, e-commerce PDP, Print A4, Email banner.
--
-- This table tracks each derivative format URL so the client gallery can
-- offer one-click download per channel + a ZIP of all formats.
--
-- Reference: .planning/studio/IMPLEMENTATION-PLAN.md §2.1
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.studio_output_formats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id UUID NOT NULL REFERENCES public.collection_assets(id) ON DELETE CASCADE,
  format_key TEXT NOT NULL,
  storage_url TEXT NOT NULL,
  width INTEGER CHECK (width IS NULL OR width > 0),
  height INTEGER CHECK (height IS NULL OR height > 0),
  file_size INTEGER CHECK (file_size IS NULL OR file_size > 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  UNIQUE(asset_id, format_key)
);

COMMENT ON TABLE public.studio_output_formats IS
  'Aimily Studio · per-format derivative URLs for each Studio output. Generated by sharp post-processing pipeline after master image is created.';

COMMENT ON COLUMN public.studio_output_formats.format_key IS
  'Format identifier. One of: instagram-square, instagram-portrait, instagram-story, tiktok-vertical, pinterest, facebook-ad, linkedin, twitter, web-hero, ecommerce-pdp, print-a4, email-banner';

CREATE INDEX idx_studio_output_formats_asset_id
  ON public.studio_output_formats(asset_id);

-- RLS · user can SELECT formats for their own Studio assets only
ALTER TABLE public.studio_output_formats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "studio_output_formats_owner_select"
  ON public.studio_output_formats FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.collection_assets ca
    INNER JOIN public.studio_projects sp ON sp.id = ca.studio_project_id
    WHERE ca.id = studio_output_formats.asset_id
      AND sp.user_id = auth.uid()
  ));

-- INSERT/UPDATE/DELETE only by service_role (post-processing job runs server-side)
