
-- Paso 2 foundation per roadmap_aimily-strategy-paso-2-3-2026-05-16.md:
-- 1. tenant_brand_profile JSONB on strategy_tenants — for STANDALONE
--    tenants that don't have aimily Block 1 brand DNA workspace. Mirrors
--    the shape of Block 1's BrandIdentityProposal so creative discovery
--    + new SKU proposers can read uniformly regardless of source.
-- 2. strategy_recommended_palettes — lightweight per-family palette
--    suggestions generated by recommendPalette(). Scoped to a run so the
--    customer sees palette evolution across re-runs.

ALTER TABLE strategy_tenants
  ADD COLUMN IF NOT EXISTS tenant_brand_profile jsonb DEFAULT '{}'::jsonb;

COMMENT ON COLUMN strategy_tenants.tenant_brand_profile IS
  'Standalone-mode brand DNA shape (mirrors Block 1 BrandIdentityProposal): brand_archetype, brand_values[], tone_of_voice, visual_anchors {colors[], typography[], photography_style}, target_consumer_hint, positioning, website, instagram. Populated at onboarding via researchBrand() auto-discovery or manually by the tenant admin. Read by loadStrategyTenantContext() for AI generators.';

CREATE TABLE strategy_recommended_palettes (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  tenant_id uuid NOT NULL REFERENCES strategy_tenants(id) ON DELETE CASCADE,
  run_id uuid NOT NULL REFERENCES strategy_analysis_runs(id) ON DELETE CASCADE,
  family_code text NOT NULL,
  palette jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- palette shape:
  -- {
  --   colors: [
  --     { name, hex, confidence, source_winner_ref?, rationale, dna_alignment, tension? }
  --   ],
  --   brief_alignment: 0-1,
  --   trend_signals_used: [...],
  --   generated_at: ISO timestamp,
  --   algorithm: 'recommend-palette-v1'
  -- }
  applied_to_brief_id uuid REFERENCES strategy_creative_briefs(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX strategy_recommended_palettes_tenant_idx ON strategy_recommended_palettes(tenant_id);
CREATE INDEX strategy_recommended_palettes_run_idx ON strategy_recommended_palettes(run_id);
CREATE INDEX strategy_recommended_palettes_family_idx ON strategy_recommended_palettes(run_id, family_code);
CREATE INDEX strategy_recommended_palettes_brief_idx ON strategy_recommended_palettes(applied_to_brief_id);
CREATE INDEX strategy_recommended_palettes_creator_idx ON strategy_recommended_palettes(created_by);

ALTER TABLE strategy_recommended_palettes ENABLE ROW LEVEL SECURITY;

CREATE POLICY strategy_recommended_palettes_read ON strategy_recommended_palettes
  FOR SELECT TO authenticated
  USING (strategy_user_is_tenant_member(tenant_id));

CREATE POLICY strategy_recommended_palettes_insert ON strategy_recommended_palettes
  FOR INSERT TO authenticated
  WITH CHECK (strategy_user_is_tenant_member(tenant_id, 'analyst'::strategy_tenant_role));

CREATE POLICY strategy_recommended_palettes_update ON strategy_recommended_palettes
  FOR UPDATE TO authenticated
  USING (strategy_user_is_tenant_member(tenant_id, 'analyst'::strategy_tenant_role))
  WITH CHECK (strategy_user_is_tenant_member(tenant_id, 'analyst'::strategy_tenant_role));

CREATE POLICY strategy_recommended_palettes_delete ON strategy_recommended_palettes
  FOR DELETE TO authenticated
  USING (strategy_user_is_tenant_member(tenant_id, 'admin'::strategy_tenant_role));

COMMENT ON TABLE strategy_recommended_palettes IS
  'Per-family color palette recommendations generated by recommendPalette(). 5-7 colors with hex + confidence + bridges to winning SKUs + brand-DNA alignment notes + tension flags. Customer can apply a palette to a creative brief (sets applied_to_brief_id).';
